### ISSUE TITLE
Can't Post on my Own Node

### ISSUE THREAD

**Issue by 4nanook** [friendica/friendica#10162]
- [ x] I have searched open and closed issues for duplicates

### Bug Description

Can't Post on my own node: https://friendica.eskimo.com/

### Steps to Reproduce

1. Go to "Home"
2. Click on Share window
3. Type something in the fields
4. Hit Preview - Post appears as expected
5. Hit Share - Post does not appear

Actual Result:

Post does not show after posting or in the feed at all.
Expected Result:

Expect to see the post.

### Screenshots

![testpost-before-preview](https://user-images.githubusercontent.com/3466797/115659572-94aa3c00-a2ef-11eb-94d5-48b7456da347.png)
![testpost-preview](https://user-images.githubusercontent.com/3466797/115659579-98d65980-a2ef-11eb-8eab-60d747bef797.png)
![testpost-share](https://user-images.githubusercontent.com/3466797/115659593-9d9b0d80-a2ef-11eb-9bff-b6e78821464f.png)

Also I turned on debugging and posted here is the log.
[friendica.log](https://github.com/friendica/friendica/files/6355674/friendica.log)

### Platform Info

Friendica Version:

Version
    Friendica 'Red Hot Poker' 2021.03-dev - 1406 

Friendica Source: 
Github
PHP version:
PHP 7.4.16 (cli) (built: Mar  5 2021 07:54:38) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.16, Copyright (c), by Zend Technologies

SQL version:
mysql  Ver 15.1 Distrib 10.5.9-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by 4nanook** [comment]
Ok, it gets even stranger, even though my posts don't show up on my friendica node, they DO show up on my hubzilla node even though I posted them on friendica and they did not show up there.

**Comment by 4nanook** [comment]
Well now one of my posts DID show up on my machine about half hour later which is odd since hubzilla and it are on the same physical box and it showed up right away in hubzilla and the work queue is NOT backed up.

**Comment by 4nanook** [comment]
This is what the load looks like, this is on a six core, twelve thread machine with 4.2 Ghz CPU, so there are at least 3-4 idle cores.

top - 22:46:38 up  7:39,  1 user,  load average: 1.30, 3.13, 2.87
Tasks: 275 total,   1 running, 274 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.8 us,  0.4 sy,  0.0 ni, 98.8 id,  0.0 wa,  0.0 hi,  0.1 si,  0.0 st
MiB Mem :  56254.9 total,  27887.3 free,  15017.0 used,  13350.6 buff/cache
MiB Swap: 131072.0 total, 131072.0 free,      0.0 used.  40484.0 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND 
   2863 root      20   0 4506944 100252   6464 S   3.0   0.2  15:21.82 fail2ba+
 575661 friendi+  20   0  363692  57728  43564 S   0.7   0.1   0:00.16 php-cgi 
    865 root      20   0  261768  18928  16460 S   0.3   0.0   1:46.78 Network+
   1071 tomcat    20   0   18.8g 684292  33848 S   0.3   1.2   0:56.59 java    
   1244 redis     20   0   52796   5208   3592 S   0.3   0.0   0:50.20 redis-s+
   1296 mysql     20   0   44.2g  12.6g  61700 S   0.3  23.0  46:53.99 mariadbd
   3046 lightdm   20   0  570736  49080  41476 S   0.3   0.1   0:19.56 slick-g+
 566475 root       0 -20       0      0      0 I   0.3   0.0   0:01.40 kworker+
      1 root      20   0  167960  11940   8448 S   0.0   0.0   0:18.96 systemd 
      2 root      20   0       0      0      0 S   0.0   0.0   0:00.05 kthreadd
      3 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 rcu_gp  
      4 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 rcu_par+
      6 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kworker+
      9 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 mm_perc+
     10 root      20   0       0      0      0 S   0.0   0.0   0:00.00 rcu_tas+
     11 root      20   0       0      0      0 S   0.0   0.0   0:00.00 rcu_tas+
     12 root      20   0       0      0      0 S   0.0   0.0   0:00.00 rcu_tas+

**Comment by 4nanook** [comment]
Ah no it didn't that post was from hubzilla, so my posts from hubzilla show up on hubzilla and friendica, but my post on friendica shows up on hubzilla but not friendica.  Makes no sense.

**Comment by annando** [comment]
have a look for entries with "DB Error" in your Friendica log file.

**Comment by 4nanook** [comment]
```
nanook@nanook:~/Desktop$ grep 'DB error' friendica.log
nanook@nanook:~/Desktop$ 
```

None in the friendica log and also ZERO errors in the mariadb log.

**Comment by annando** [comment]
It's with a big "E".

**Comment by 4nanook** [comment]
```
nanook@nanook:~/Desktop$ grep -i 'DB error' friendica.log
nanook@nanook:~/Desktop$ 
```

There is a case independent grep, big E or little, no error, AND again no error in the MariaDB logs.

**Comment by 4nanook** [comment]
I discovered that only >I< can not see my own posts.  If I post as me, then login as a different user, I can see my post, but I can not see my post as myself.

**Comment by 4nanook** [comment]
Ah it gets even stranger.   After logging out as my test user and logging in as myself, I can STILL see my posts.  But I can't see new posts I make without logging out and back in again.

**Comment by 4nanook** [comment]
Wasn't seeing any DB Errors at the time you asked, but today saw this:
```
2021-04-24T00:34:03Z worker [ERROR]: DB Error {"code":1264,"error":"Out of range value for column 'registered-users' at row 1","callstack":"DBA::update, GServer::detect, GServer::check, UpdateGServer::execute, Worker::execFunction, Worker::execute, Worker::processQueue","params":"UPDATE `gserver` SET `detection-method` = 16, `platform` = 'mastodon', `network` = 'apub', `site_name` = 'The Entire World', `info` = 'You think your fake numbers are impressive? Well, this instance contains all living humans.', `version` = '2.9.2+antifa', `registered-users` = 7770914602, `directory-type` = 0, `poco` = '', `url` = 'https:\/\/you-think-your-fake-numbers-are-impressive.well-this-instance-contains-all-living-humans.lubar.me', `nurl` = 'http:\/\/you-think-your-fake-numbers-are-impressive.well-this-instance-contains-all-living-humans.lubar.me', `next_contact` = '2021-05-01 00:34:03', `last_contact` = '2021-04-24 00:34:03', `failed` = 0 WHERE (`nurl` = 'http:\/\/you-think-your-fake-numbers-are-impressive.well-this-instance-contains-all-living-humans.lubar.me')"} - {"file":"Database.php","line":765,"function":"e","uid":"ee609f","process_id":82428}
```

**Comment by MrPetovan** [comment]
This is a known troll instance, please add `you-think-your-fake-numbers-are-impressive.well-this-instance-contains-all-living-humans.lubar.me` to your server block list. However this wouldn't have anything to do with your original issue.

**Comment by 4nanook** [comment]
I went to that domain and it didn't even look like a real site, links went to other places, no user profiles instead goes to a Wikipedia world population page, so added it for what it's worth but any idea on the original issue?

**Comment by 4nanook** [comment]
Can anyone help me get this fixed?  I'm actually getting to the point of having a substantial user base so hate to have to abandon and go to a different platform now.

Here are some more DB errors:
```
2021-04-25T02:02:13Z index [ERROR]: DB Error {"code":1406,"error":"Data too long for column 'url' at row 1","callstack":"Media::insert, Processor::storeAttachmentAsMedia, Processor::constructAttachList, Processor::updateItem, Receiver::processActivity, Receiver::processInbox, Inbox::rawContent, call_user_func","params":"INSERT INTO `post-media` (`uri-id`, `type`, `url`, `mimetype`, `height`) VALUES (774760, 16, 'magnet:?xs=https%3A%2F%2Fvideos.lukesmith.xyz%2Flazy-static%2Ftorrents%2F69a285b1-454f-41bc-bb31-2686b6f7150a-1080.torrent&xt=urn:btih:beea58577a63cd19067aad7047ba7f61617965f8&dn=REACTS%3A+%F0%9F%96%90%EF%B8%8F%F0%9F%98%AE%F0%9F%96%90%EF%B8%8F+The+Fish+%22shell%22+is+not+a+shell+and+is+cringe+to+use.&tr=https%3A%2F%2Fvideos.lukesmith.xyz%2Ftracker%2Fannounce&tr=wss%3A%2F%2Fvideos.lukesmith.xyz%3A443%2Ftracker%2Fsocket&ws=https%3A%2F%2Fvideos.lukesmith.xyz%2Fstatic%2Fwebseed%2F69a285b1-454f-41bc-bb31-2686b6f7150a-1080.mp4', 'application\/x-bittorrent;x-scheme-handler\/magnet', 1080) ON DUPLICATE KEY UPDATE `uri-id` = 774760, `type` = 16, `url` = 'magnet:?xs=https%3A%2F%2Fvideos.lukesmith.xyz%2Flazy-static%2Ftorrents%2F69a285b1-454f-41bc-bb31-2686b6f7150a-1080.torrent&xt=urn:btih:beea58577a63cd19067aad7047ba7f61617965f8&dn=REACTS%3A+%F0%9F%96%90%EF%B8%8F%F0%9F%98%AE%F0%9F%96%90%EF%B8%8F+The+Fish+%22shell%22+is+not+a+shell+and+is+cringe+to+use.&tr=https%3A%2F%2Fvideos.lukesmith.xyz%2Ftracker%2Fannounce&tr=wss%3A%2F%2Fvideos.lukesmith.xyz%3A443%2Ftracker%2Fsocket&ws=https%3A%2F%2Fvideos.lukesmith.xyz%2Fstatic%2Fwebseed%2F69a285b1-454f-41bc-bb31-2686b6f7150a-1080.mp4', `mimetype` = 'application\/x-bittorrent;x-scheme-handler\/magnet', `height` = 1080"} - {"file":"Database.php","line":765,"function":"e","uid":"fdff56","process_id":1523064}
2021-04-25T03:02:25Z index [ERROR]: DB Error {"code":1406,"error":"Data too long for column 'url' at row 1","callstack":"Media::insert, Processor::storeAttachmentAsMedia, Processor::constructAttachList, Processor::updateItem, Receiver::processActivity, Receiver::processInbox, Inbox::rawContent, call_user_func","params":"INSERT INTO `post-media` (`uri-id`, `type`, `url`, `mimetype`, `height`) VALUES (774760, 16, 'magnet:?xs=https%3A%2F%2Fvideos.lukesmith.xyz%2Flazy-static%2Ftorrents%2F69a285b1-454f-41bc-bb31-2686b6f7150a-1080.torrent&xt=urn:btih:beea58577a63cd19067aad7047ba7f61617965f8&dn=REACTS%3A+%F0%9F%96%90%EF%B8%8F%F0%9F%98%AE%F0%9F%96%90%EF%B8%8F+The+Fish+%22shell%22+is+not+a+shell+and+is+cringe+to+use.&tr=https%3A%2F%2Fvideos.lukesmith.xyz%2Ftracker%2Fannounce&tr=wss%3A%2F%2Fvideos.lukesmith.xyz%3A443%2Ftracker%2Fsocket&ws=https%3A%2F%2Fvideos.lukesmith.xyz%2Fstatic%2Fwebseed%2F69a285b1-454f-41bc-bb31-2686b6f7150a-1080.mp4', 'application\/x-bittorrent;x-scheme-handler\/magnet', 1080) ON DUPLICATE KEY UPDATE `uri-id` = 774760, `type` = 16, `url` = 'magnet:?xs=https%3A%2F%2Fvideos.lukesmith.xyz%2Flazy-static%2Ftorrents%2F69a285b1-454f-41bc-bb31-2686b6f7150a-1080.torrent&xt=urn:btih:beea58577a63cd19067aad7047ba7f61617965f8&dn=REACTS%3A+%F0%9F%96%90%EF%B8%8F%F0%9F%98%AE%F0%9F%96%90%EF%B8%8F+The+Fish+%22shell%22+is+not+a+shell+and+is+cringe+to+use.&tr=https%3A%2F%2Fvideos.lukesmith.xyz%2Ftracker%2Fannounce&tr=wss%3A%2F%2Fvideos.lukesmith.xyz%3A443%2Ftracker%2Fsocket&ws=https%3A%2F%2Fvideos.lukesmith.xyz%2Fstatic%2Fwebseed%2F69a285b1-454f-41bc-bb31-2686b6f7150a-1080.mp4', `mimetype` = 'application\/x-bittorrent;x-scheme-handler\/magnet', `height` = 1080"} - {"file":"Database.php","line":765,"function":"e","uid":"848183","process_id":1561937}
2021-04-25T03:59:08Z index [ERROR]: DB Error {"code":1054,"error":"Unknown column 'type' in 'where clause'","callstack":"Post::select, Item::deleteForUser, api_fr_photo_delete, api_call, api_content, LegacyModule::runModuleFunction, LegacyModule::content, call_user_func","params":"SELECT `id`, `uid`, `uri-id` FROM `post-user-view` WHERE (`uid` = 16 AND `resource-id` = '1717115768607819ad8592a007579295' AND `type` = 'photo')"} - {"file":"Database.php","line":662,"function":"p","uid":"fbdec0","process_id":1596084}
2021-04-25T05:56:38Z index [ERROR]: DB Error {"code":1406,"error":"Data too long for column 'k' at row 1","callstack":"Media::insert, Processor::storeAttachmentAsMedia, Processor::constructAttachList, Processor::createItem, Receiver::processActivity, Receiver::processInbox, Inbox::rawContent, call_user_func","params":"REPLACE `cache` (`k`, `v`, `expires`, `updated`) VALUES ('https:\/\/bibliogram.nixnet.services\/imageproxy?url=https%3A%2F%2Fscontent-dfw5-2.cdninstagram.com%2Fv%2Ft51.2885-15%2Fe35%2Fp1080x1080%2F176448967_124798349704212_1166991407079141830_n.jpg%3Ftp%3D1%26_nc_ht%3Dscontent-dfw5-2.cdninstagram.com%26_nc_cat%3D1%26_nc_ohc%3DLc2_Tm2Mvh0AX9S84l_%26edm%3DAAuNW_gAAAAA%26ccb%3D7-4%26oh%3D267f0d9d64ca7a6b9398197130b3ac19%26oe%3D60AB92E7%26_nc_sid%3D498da5', 'a:0:{}', '2021-04-25 06:01:38', '2021-04-25 05:56:38')"} - {"file":"Database.php","line":765,"function":"e","uid":"7d5ed3","process_id":1681545}
2021-04-25T08:14:03Z worker [ERROR]: DB Error {"code":1452,"error":"Cannot add or update a child row: a foreign key constraint fails (`friendica`.`contact-relation`, CONSTRAINT `contact-relation_ibfk_2` FOREIGN KEY (`relation-cid`) REFERENCES `contact` (`id`) ON DELETE CASCADE)","callstack":"DBA::insert, Relation::discoverByUrl, ContactDiscovery::execute, Worker::execFunction, Worker::execute, Worker::processQueue","params":"INSERT INTO `contact-relation` (`cid`, `relation-cid`, `follows`, `follow-updated`) VALUES (5333, 442041, 1, '2021-04-25 08:14:03') ON DUPLICATE KEY UPDATE `cid` = 5333, `relation-cid` = 442041, `follows` = 1, `follow-updated` = '2021-04-25 08:14:03'"} - {"file":"Database.php","line":765,"function":"e","uid":"46b5e1","process_id":1847705}
2021-04-25T08:35:08Z worker [ERROR]: DB Error {"code":1452,"error":"Cannot add or update a child row: a foreign key constraint fails (`friendica`.`contact-relation`, CONSTRAINT `contact-relation_ibfk_2` FOREIGN KEY (`relation-cid`) REFERENCES `contact` (`id`) ON DELETE CASCADE)","callstack":"DBA::insert, Relation::discoverByUrl, ContactDiscovery::execute, Worker::execFunction, Worker::execute, Worker::processQueue","params":"INSERT INTO `contact-relation` (`cid`, `relation-cid`, `follows`, `follow-updated`) VALUES (16918, 442084, 1, '2021-04-25 08:35:08') ON DUPLICATE KEY UPDATE `cid` = 16918, `relation-cid` = 442084, `follows` = 1, `follow-updated` = '2021-04-25 08:35:08'"} - {"file":"Database.php","line":765,"function":"e","uid":"604f55","process_id":1907508}
2021-04-25T08:40:33Z worker [ERROR]: DB Error {"code":1452,"error":"Cannot add or update a child row: a foreign key constraint fails (`friendica`.`contact-relation`, CONSTRAINT `contact-relation_ibfk_2` FOREIGN KEY (`relation-cid`) REFERENCES `contact` (`id`) ON DELETE CASCADE)","callstack":"DBA::insert, Relation::discoverByUrl, ContactDiscovery::execute, Worker::execFunction, Worker::execute, Worker::processQueue","params":"INSERT INTO `contact-relation` (`cid`, `relation-cid`, `follows`, `follow-updated`) VALUES (8089, 442116, 1, '2021-04-25 08:40:33') ON DUPLICATE KEY UPDATE `cid` = 8089, `relation-cid` = 442116, `follows` = 1, `follow-updated` = '2021-04-25 08:40:33'"} - {"file":"Database.php","line":765,"function":"e","uid":"5ab0b1","process_id":1907510}
```

**Comment by AlfredSK** [comment]
> unknown column 'type'

Looks like the db structure isn't right.

Try to run `bin/console dbstructure update -f` 

Also, you are on develop. In the current RC branch a lot of things have been fixed. You may try to update/switch to the current RC code.

**Comment by 4nanook** [comment]
Excuse my ignorance but how do I switch to the current RC code?

**Comment by 4nanook** [comment]
Ok I switched to 2021.03-rc and still can't see my own posts.

**Comment by AlfredSK** [comment]
Have you tried to run the dbstructure command before you switched like I wrote in my previous comment?

RC: The DB update and postupdate will take some time. When those are finished please run the dbstructure command and have a look on the output.

**Comment by 4nanook** [comment]
There was no output, just returned to the command prompt, ran it before and after.  Also check dbstructure does not show any errors:

Database structure update 1413 was successfully applied.
Report Bug
Database: 0/0, Network: 0, Rendering: 0, Session: 0, I/O: 0, Other: 0.25, Total: 0.25
Class-Init: 0.09, Boot: 0.024, Init: 0.001, Content: 0.119, Other: 0.016, Total: 0.25

**Comment by AlfredSK** [comment]
Ok. When everything is finished the /friendica page of your node should show DB version 1413/1413 and post update version 1400/1400.

When this is the case you should check for 'DB Error' entries in your Friendica log again.

**Comment by 4nanook** [comment]
Friendica

This is Friendica, version 2021.03-rc that is running at the web location https://friendica.eskimo.com. The database version is 1413/1413, the post update version is 1400/1400.

I have zero'd the log

Then I posted a test message.  It did not show up in either Local or Global Community streams, yet, it showed up immediately on my hubzilla node, and on hubzilla it shows up with correct name and timestamp, but if I search on friendica I find it with a time stamp an hour off and showing garbage in the username.  And there are no Database errors in the log after the post. See the two screen shots below:

![hubzilla](https://user-images.githubusercontent.com/3466797/116040088-6777c980-a620-11eb-89f2-0462673dc351.png)
![friendica](https://user-images.githubusercontent.com/3466797/116040099-6ba3e700-a620-11eb-872c-d00ca776ca77.png)

**Comment by 4nanook** [comment]
Since upgrading to 2021.03-rc the situation has gotten worse.  Now my posts just go into the ether and show up neither on other sites nor locally if I logout and log back in.  And after I post I get this warning in the logs:
2021-04-26T22:42:29Z index [WARNING]: Invalid HTTP signature, message will be discarded. [] - {"file":"Receiver.php","line":115,"function":"processInbox","uid":"46d364","process_id":633708}

**Comment by 4nanook** [comment]
Upgraded Friendica to:

This is Friendica, version 2021.06-dev that is running at the web location https://friendica.eskimo.com. The database version is 1414/1414, the post update version is 1400/1400.

Still can't post from my node, other users seem able to.

**Comment by 4nanook** [comment]
This DB Error occurred after the upgrade:
```
2021-04-27T21:17:25Z index [ERROR]: DB Error {"code":1054,"error":"Unknown column 'type' in 'where clause'","callstack":"Post::select, Item::deleteForUser, api_fr_photo_delete, api_call, api_content, LegacyModule::runModuleFunction, LegacyModule::content, call_user_func","params":"SELECT `id`, `uid`, `uri-id` FROM `post-user-view` WHERE (`uid` = 16 AND `resource-id` = '1324353016607b82ba815b6752708303' AND `type` = 'photo')"} - {"file":"Database.php","line":662,"function":"p","uid":"f7cffb","process_id":1848983}
```

**Comment by annando** [comment]
When other users on your system can work, then there is something weird with your account only. Question is what. Since no one had reported this before, I'm currently clueless.

**Comment by 4nanook** [comment]
At one point early on my account had become blocked on my server.  Since
my account is the only admin account how that happened is a mystery as well.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by 4nanook** [comment]
I noticed something weird when I try to use mysql, some tables will
not allow me to use describe on them.

     Eh never mind, they had a '-' in the name and I just had to quote them.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by 4nanook** [comment]
Is there any place where the various tables friendica uses are documents, what columns are for what, etc?

**Comment by tobiasd** [comment]
Yes, there is the `/doc/database.md` file that should include this info I think.

**Comment by 4nanook** [comment]
Thank you, at least gives me something to investigate.

**Comment by annando** [comment]
more information you find in the files dbstructure.config.php and dbview.config.php in the "static" folder.

But since you said that your problem doesn't occur to other users on your machine, it cannot be a database structure problem.

**Comment by 4nanook** [comment]
I'm not thinking structure so much as incorrect data.  I don't know how
I did it before but early on I managed to get myself blocked.  Hypolite Petovan 
was able to determine that from my logs and gave me an SQL statement that 
fixed.  Now I'm wondering if I've got myself ignored somehow.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by 4nanook** [comment]
I haven't seen any posts in my network recently so I created a test user "testuser" to verify that other users can still post and it posts okay.  So now at least I have to uses and can stare and compare at database entries between them so see what is different. If anyone can point me at specific tables or columns that might be relevant it would be appreciated, else I will continue to grope.

**Comment by 4nanook** [comment]
Well I've spent hours staring and comparing and still missing whatever is wrong.  I turned on debug and the amount of data generated for one post seems overwhelming.  I would really like to understand this better, it seems to create a UID for the post and then delivers to various contacts?  The internal logic does not seem very efficient, seems to do a lot of looping.  I turned off blockem' about the only addon relating to blocking I had enabled, no difference.  I see some debug messages telling the UID already exists, don't know if this is a concern or not.  Any hints as to where to look to narrow down the search would be appreciated.  I would just kill this account and create a new if I did not already have a large number of contacts associated with it and also I want to understand what is happening in case it happens to someone else.  I have 132 users on my node now which I realize isn't huge but this is about my 20th experiment in social media and thus far the only one that has gained any traction.

**Comment by 4nanook** [comment]
If I search for the post I made with my account using my test user account it finds it, but if I perform the same search as me, it does not find it.

**Comment by 4nanook** [comment]
Me too, I've spent a lot of time digging through database tables and not
finding anything obviously out of place but my lack of familiarity with
friendica's database and PHP does not help.  I am a C/C++ person myself, I
understand most of the concepts involved but not the syntax.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by 4nanook** [comment]
I found what was wrong in the database and fixed with the following query:
```
UPDATE `user-contact` SET `ignored` = 0 WHERE `uid` = 1 AND `cid` = (SELECT `id` FROM `contact` WHERE `uid` = 0 AND `nurl` = "http://friendica.eskimo.com/profile/nanook" LIMIT 1);
```
However, I do not know what cause this to get set, just like I don't know how blocked got set before.

**Comment by MrPetovan** [comment]
It looks like you managed to ignore yourself, which would make your posts invisible to you. This isn't great but at least we have something to suggest to check to people with the same issue, thank you for your time spent troubleshooting this!

**Comment by 4nanook** [comment]
I'm going to submit a feature request based upon my experience with blocking and ignoring myself.

**Comment by MrPetovan** [comment]
Thank you for your work!

**Comment by 4nanook** [comment]
Thank you for the support you've provided regarding the various issues I've run up against and a good web application.  Resource intensive to be sure but it is the first social media project that I've had running here that has actually gained traction.  We've picked up 134 users in the 4 months I've had it online.

**Comment by MrPetovan** [comment]
I'm glad it's working out for you.

**Comment by 4nanook** [comment]
Yep same issue.  This time I made a note of the query in case it happens again in the future.  Thank you.

**Comment by 4nanook** [comment]
And just a general note regarding 2021.12-rc - 1449, seems to be MUCH smoother and eliminated the load spikes I was experiencing.
