### ISSUE TITLE
messages do not arrive reliably

### ISSUE THREAD

**Issue by rnwgnr** [friendica/friendica#10254]
- [x] I have searched open and closed issues for duplicates
May be related to #9544 and/or #6395

### Bug Description
My instance does not seem to get new messages over ActivityPub reliably. E.g. a test message explizitly adressed to my user from nerdculture.de does not arrive on my instance.

### Steps to Reproduce
???

### Log
the log shows a lot of the following errors:
```
2021-05-16T10:44:16Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"0ef562","process_id":1340230}
2021-05-16T10:44:39Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"469feb","process_id":1341924}
2021-05-16T10:44:44Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"9e3d45","process_id":1341924}
2021-05-16T10:44:52Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"7d7409","process_id":1341924}
2021-05-16T10:44:57Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"9f7ec7","process_id":1341924}
2021-05-16T10:45:02Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"0437bf","process_id":1341924}
2021-05-16T10:45:05Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"1ad88c","process_id":1341924}
2021-05-16T10:45:39Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"14d7bc","process_id":1347908}
2021-05-16T10:45:44Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"309100","process_id":1347908}
2021-05-16T10:46:00Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"e70a50","process_id":1348794}
2021-05-16T10:46:04Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"00fb38","process_id":1348794}
2021-05-16T10:46:14Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"75d218","process_id":1348794}
2021-05-16T10:46:35Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"d2207f","process_id":1348794}
2021-05-16T10:46:40Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"9acc21","process_id":1351120}
2021-05-16T10:46:42Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"cf5023","process_id":1348794}
```

### Actual Result:
Messages do not arrive, but sometimes they get through.

### Expected Result:
Messages arrive reliably 

### Platform Info
Friendica Version: 2021.04
Friendica Source: git/stable
PHP version: 7.4.14
PHP memory limit: 256MB
SQL version: MariaDB 10.5

**Comment by rnwgnr** [comment]
I've increased the PHP memory limit to 1024MB but the errors still show up:
```
2021-05-16T11:12:50Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"a2b16d","process_id":1496223}
2021-05-16T11:13:11Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"82cf2f","process_id":1505306}
2021-05-16T11:13:35Z worker [ERROR]: compacting error {"worker_id":"2a7ca73","worker_cmd":"UpdateContact"} - {"file":"JsonLD.php","line":153,"function":"compact","uid":"bce056","process_id":1507731}
2021-05-16T11:13:35Z worker [ERROR]: compacting error {"worker_id":"4e70a66","worker_cmd":"UpdateContact"} - {"file":"JsonLD.php","line":153,"function":"compact","uid":"940780","process_id":1508017}
2021-05-16T11:13:50Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"5413ba","process_id":1505306}
2021-05-16T11:13:55Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"761f57","process_id":1505306}
2021-05-16T11:13:59Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"ae15f3","process_id":1505306}
2021-05-16T11:14:32Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"e6417d","process_id":1511552}
2021-05-16T11:14:36Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"bca1ee","process_id":1511552}
2021-05-16T11:14:40Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"72484f","process_id":1511552}
2021-05-16T11:14:41Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"9aa2c7","process_id":1511816}
2021-05-16T11:14:42Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"fdd656","process_id":1511552}
2021-05-16T11:14:52Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"0d92a8","process_id":1511816}
2021-05-16T11:14:58Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"f38f50","process_id":1511552}
2021-05-16T11:15:00Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"4fe4db","process_id":1511816}
2021-05-16T11:15:05Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"8736e5","process_id":1511816}
```

**Comment by AlfredSK** [comment]
I have these JSON-LD compacting errors too. As far as I understand the compacting is the process to transform JSON or JSON-LD into a shorter, more human readable format according to a particular context.

I guess this happens when we receive unexpected or malformed items. With a higher log level you possibly can find out more by showing all lines with the given 'process_id'.

**Comment by AlfredSK** [comment]
Example:

```
2021-05-16T10:58:49Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"2f8ac7","process_id":1472847}
2021-05-16T10:58:49Z index [NOTICE]: Unable to retrieve AP contact for actor - message is discarded {"actor":null} - {"file":"Receiver.php","line":104,"function":"processInbox","uid":"2f8ac7","process_id":1472847}
```

Here you see the actual problem. We are not able to retrieve the contact from the remote server. I guess that means we are also not able to check if the actor is valid. And because we can not check that we are discarding the message.

**Comment by rnwgnr** [comment]
Hi,

on `debug`level, the log looks pretty much the same as yours, e.g.:
```
2021-05-16T11:47:25Z index [DEBUG]: Contact found {"url":"rwa@scl.clttr.info","uid":0,"update":false,"cid":6} - {"file":"Contact.php","line":1063,"function":"getIdForURL","uid":"eb48ea","process_id":1681715}
2021-05-16T11:47:34Z index [ERROR]: compacting error [] - {"file":"JsonLD.php","line":153,"function":"compact","uid":"ace454","process_id":1681715}
2021-05-16T11:47:34Z index [NOTICE]: Unable to retrieve AP contact for actor - message is discarded {"actor":null} - {"file":"Receiver.php","line":104,"function":"processInbox","uid":"ace454","process_id":1681715}
2021-05-16T11:47:34Z index [INFO]: http_status_exit 202 [] - {"file":"System.php","line":125,"function":"httpExit","uid":"ace454","process_id":1681715}
```

Seems like this behaviour was already there for longer time but i didn't notice until today as almost no post is reaching my instance anymore. In march the error occured only occasionaly, now it's there for almost every message - even with the increased PHP memory limit.

**Comment by Quix0r** [comment]
Maybe related to [this](https://f.haeder.net/display/adbba6c6-8760-a112-648b-80b981300974)?

**Comment by annando** [comment]
The problem is that the URL `https://w3id.org/security/v1` doesn't resolve anymore. This URL is a central part in the `context` header of every message from every system. Since we are compacting every incoming message to improve the parsing, the compacting now fails.

**Comment by tobiasd** [comment]
My node (current 2021.06-dev) received the last posting via ActivityPub yesterday afternoon. Since then only Diaspora* and OStatus got delivered.

**Comment by atasingorneq** [comment]
The same problem here, only Diaspora posts arrive. (current 2021.06-dev - 1418)

**Comment by annando** [comment]
I made an ugly quickfix: https://github.com/friendica/friendica/pull/10253

**Comment by AlfredSK** [comment]
@Quix0r Your post (the link in your comment) didn't made it to the forum. I have the same issues at the moment. I hope the "ugly quickfix" will fix this too.

**Comment by AlfredSK** [comment]
Ok. After pulling the quick fix AP items are coming in again. Checking forum posts now.

**Comment by rnwgnr** [comment]
Can confirm that it's working again after the quickfix is applied. This should be announced and pushed to a hotfix release to make other friendica admins aware of the situation.

I have no clue why it currently is the way it is - but i suspect relying on an external URI for friendica (or atleast the AP implementation) to work is not the best idea. Can it be modified that in a way that no external ressources are required for message processing? It seems other AP systems currently don't require to said URI to be reachable.

**Comment by AlfredSK** [comment]
Ok. Forum test post made it to the forum node and has been reshared successfully by the support forum. Looks like it's working again.

**Comment by annando** [comment]
There are still problems, but I'm working on it. Bad thing is that this problem will hit all Friendica versions.

**Comment by MrPetovan** [comment]
> Can confirm that it's working again after the quickfix is applied. This should be announced and pushed to a hotfix release to make other friendica admins aware of the situation.

We have a stable release coming for June, the fix is available on the `develop` branch, we can of course notice Friendica administrators subscribed to the relevant forum but I don't think a hotfix is warranted.

**Comment by annando** [comment]
The current fix is not good enough to make it to the release. For example posts from Pleroma are currently rejected.

**Comment by very-ape** [comment]
FWIW, I experienced this problem on my 2021.04 instance this morning and have employed the following stopgap solution:
1. Downloaded the missing file [from Archive.org](https://web.archive.org/web/20210506031921/https://w3id.org/security/v1)
2. Added a server entry in Nginx to serve static files at the hostname 'w3c-mock', then created a "security" directory and moved the missing file to that directory, renaming it to "v1"
3. Added an entry in my /etc/hosts to point w3c-mock to Nginx.
4. Applied the following patch

```
diff --git a/src/Util/JsonLD.php b/src/Util/JsonLD.php
index a0a272fdd..87add07e0 100644
--- a/src/Util/JsonLD.php
+++ b/src/Util/JsonLD.php
@@ -114,7 +114,8 @@ class JsonLD
                jsonld_set_document_loader('Friendica\Util\JsonLD::documentLoader');
 
                $context = (object)['as' => 'https://www.w3.org/ns/activitystreams#',
-                       'w3id' => 'https://w3id.org/security#',
+                       //'w3id' => 'https://w3id.org/security#',
+                       'w3id' => 'http://w3c-mock/security#',
                        'ldp' => (object)['@id' => 'http://www.w3.org/ns/ldp#', '@type' => '@id'],
                        'vcard' => (object)['@id' => 'http://www.w3.org/2006/vcard/ns#', '@type' => '@id'],
                        'dfrn' => (object)['@id' => 'http://purl.org/macgirvin/dfrn/1.0/', '@type' => '@id'],
@@ -134,7 +135,8 @@ class JsonLD
                // Workaround for servers with missing context
                // See issue https://github.com/nextcloud/social/issues/330
                if (!empty($json['@context']) && is_array($json['@context'])) {
-                       $json['@context'][] = 'https://w3id.org/security/v1';
+                       //$json['@context'][] = 'https://w3id.org/security/v1';
+                       $json['@context'][] = 'http://w3c-mock/security/v1';
                }
 
                // Trying to avoid memory problems with large content fields
```

Sharing just in case someone needs an alternative workaround immediately.

(In hindsight, I suppose I could have just added a location entry to my existing Friendica Nginx configuration and used that.)

**Comment by MrPetovan** [comment]
@annando is working on a fix to do just that as well, use a local node's route to host the same file.

**Comment by annando** [comment]
The W3C restored the file, so everything should be fine. But the current fix now serves some known definitions locally to avoid further problems.

**Comment by MrPetovan** [comment]
Do you consider #10257 to fix this issue?

**Comment by annando** [comment]
@MrPetovan yes, this should fix it.

**Comment by rnwgnr** [comment]
As far is i can check everything is back to normal again. 

Thank you very much @annando for the quick response.

**Comment by Quix0r** [comment]
Not fully solved! Go [here](https://mastodon.social/@stman/103601365987603437) and click on favorite or repeat and then enter your webfinger ID ... It ends up having the status' URL detected as profile URL. :-(

**Comment by Quix0r** [comment]
> The W3C restored the file, so everything should be fine. But the current fix now serves some known definitions locally to avoid further problems.

Let's put that on Friendica's main server and reference all URLs there. Just as a backup ...

**Comment by MrPetovan** [comment]
I like @annando 's solution better, since we are a decentralized social network, let's host this file on every single Friendica server and make them reference their own file in their own messages. If a server goes down, all the messages it issued won't be able to be compacted, which isn't that much of a problem since the server went down, and it places less of a burden on the Friendica team.
