### ISSUE TITLE
Cat Avatar Generator usable for administrators only

### ISSUE THREAD

**Issue by Tealk** [friendica/friendica#10314]
- [ x ] I have searched open and closed issues for duplicates

### Bug Description

User can not generate random cat, only as admin the function works. I have also tried it on another instance there I have the same problem.

### Steps to Reproduce

1.  enable Cat Avatar Generator - 1.1
2.  got to Settings -> Addons -> Cat Profile Picture Settings
3.  click on random cat

Actual Result:

No error is displayed, not even in the console

Expected Result:

When you click on the button a new cat should appear

### Platform Info

Friendica Version:

Friendica Source: 'Siberian Iris' 2021.04 - 1413

PHP version: 7.4.18

SQL version: 10.5.10-MariaDB-1:10.5.10+maria~buster

**Comment by Tealk** [comment]
Ok I found the problem "proc_close" must be enabled. Maybe you could add that to the description?

**Comment by nupplaphil** [comment]
fixed with https://github.com/friendica/friendica-addons/pull/1129

**Comment by Tealk** [comment]
when i apply the changes it looks like this and still does not work
![image](https://user-images.githubusercontent.com/12276250/120086903-646e6e00-c0e3-11eb-9901-8ee0b3d4051b.png)

**Comment by nupplaphil** [comment]
Mhmmm... I tried it with private mode and a new created user, I'll have another look

**Comment by AlfredSK** [comment]
I checked it with 2021.06-rc. And it worked as expected.

Logged in as normal user (old test account)
Go to Addons
Open the Catavatar accordion
Click on Random Cat -> Cat changed to another cat
Click on Use this cat as profile pic -> Profile pic changed successfully to the new cat

The provided screenshot looks weird. Maybe the template isn't loaded correctly.

@Tealk Could you try to refresh your browser cache, please? Or simply do a Shift+Reload?

With Frio custom color theme:

![image](https://user-images.githubusercontent.com/3656054/120096295-ee8df500-c12a-11eb-8683-c7b806236af2.png)

**Comment by nupplaphil** [comment]
Maybe theme specific? What theme do you use?

**Comment by Tealk** [comment]
I use Frio too

but i only use the cat avatar generator addon in version 2021.06-rc the instance is still on 2021.04
i thought that the add-ons can be updated independently

**Comment by MrPetovan** [comment]
As a rule the addon version should match the Friendica core version, we can't guarantee compatibility any other way (older addons or older core)

**Comment by nupplaphil** [comment]
@Tealk did it work with the cache cleanup? I'm still able to use it properly with a "normal" user and frio ..

**Comment by Tealk** [comment]
also with cleared cache it doesn't work, but maybe it's like @MrPetovan says it's a problem because i'm still using version 2021.04 for the instance

**Comment by nupplaphil** [comment]
I see, so I'll close this issue again and please have a look after the upcoming `2021.06` release if the bug is still there and plz reopen this bug again in that case

**Comment by Tealk** [comment]
have update to i have just updated to 2021.06-rc but changing the image still only works for administrators
also on the instant https://friendica.utzer.de it does not work

**Comment by AlfredSK** [comment]
I can only assume that this issue is some add-on interoperability error. I use catavatar on my nodes and it works as expected. 

Maybe there is some hint/error in the browser console or in the Friendica log?

This is my list of add-ons:

advancedcontentfilter
blockbot
blockem
catavatar
fromapp
geocoordinates
ifttt
impressum
js_upload
langfilter
markdown
newmemberwidget
notifyall
nsfw
openstreetmap
phpmailer
showmore
startpage
superblock
tumblr
twitter
unicode_smilies
wppost

When there is no error in the logs and in the browser console you can try to disable the add-ons one by one to find the possibly problematic one.

**Comment by Tealk** [comment]
i use these: 
```advancedcontentfilter, blockem, catavatar, cookienotice, diaspora, forumdirectory, fromapp, highlightjs, ifttt, impressum, infiniteimprobabilitydrive, js_upload, leistungsschutzrecht, morepokes, newmemberwidget, nsfw, openstreetmap, phpmailer, qcomment, securemail, showmore, startpage, superblock```

**Comment by Tealk** [comment]
Secure Mail is the problem.

**Comment by nupplaphil** [comment]
A great! Thanks for the hint!

**Comment by nupplaphil** [comment]
Got the issue
![grafik](https://user-images.githubusercontent.com/379654/123525429-dfba4400-d6d0-11eb-9989-13308241610f.png)

If there's any mandatory field inside the whole addon settings, all other addons are blocked as well.
The root cause is that we use one form for the whole settings page, which causes this side effect

**Comment by AlfredSK** [comment]
A quick fix for the upcoming releases would be to make this field non-mandatory and to extend the description that the user must insert the pubkey there.

**Comment by nupplaphil** [comment]
I added the quick fix like @AlfredSK said, but I didn't had to add a description, because the mandatory field was a bug :D .. It wasn't intended by the code.

And I added a followup task for the next release: https://github.com/friendica/friendica/issues/10439

**Comment by Tealk** [comment]
works great the current commit a44a9e7
thanks to all
