### ISSUE TITLE
Wrong Language Detected for Language filter [v 2022.02]

### ISSUE THREAD

**Issue by igor-cali** [friendica/friendica#11226]
### Bug Description

Most of of the post are detected as in Persian(Farsi) by the Language Filter additional component, even if they are in different language (e.g. English or Italian)

### Steps to Reproduce

1. Language filter active: Settings -> Additional Components -> Language filter:
  - '`Use language filter`' checkbox selected
  - '`it,en,fr`' indicated as readable languages
2. Show the network stream (e.g. 'Last messages')

Actual Result:

Most of post filtered/collapsed and indicated as in Persian (Farsi), even then they are in other languages (e.g Italian or English).
See screenshot examples.

Expected Result:

Correct language identification for the filtering.

### Screenshots

![Schermata del 2022-02-08 20-43-31](https://user-images.githubusercontent.com/12466054/153063608-d3a8afdf-34d8-4ba7-a904-5a23117d3ccc.png)
![Schermata del 2022-02-08 20-45-56](https://user-images.githubusercontent.com/12466054/153063857-cc1b9f5c-9da9-4732-a7dc-5397a2b2dec9.png)
The second screenshot shows the actual language is Italian

### Platform Info
Ubuntu 20.04; Firefox browser (client)
Friendica Version: 2022.02
Nerdica pod

Friendica Source: 

PHP version:

SQL version:

**Comment by ghost** [comment]
Subscribing.

**Comment by tobiasd** [comment]
Indeed, all postings seem to be detected as _farsi_ but on my system with a probability of `0.000` so the posting is not collapsed. Could be some side-effect of #10521 @MrPetovan ?

**Comment by MrPetovan** [comment]
It seems to make sense even though I'd be hard-pressed to explain how it fails so spectacularly. I've never seen posts collapsed for allegedly being in Farsi on my node so I'm not sure I can reproduce the issue but I'll give it a shot.

**Comment by igor-cali** [comment]
**Workaround** for me: add `fa` in the list of readable languages.
E.g.: `it,en,fr` --> `it,en,fr,fa`.

**Comment by igor-cali** [comment]
> **Workaround** for me: add `fa` in the list of readable languages. E.g.: `it,en,fr` --> `it,en,fr,fa`.

The side effect is that no language is actually filtered...

**Comment by igor-cali** [comment]
> **Workaround** for me: add `fa` in the list of readable languages. E.g.: `it,en,fr` --> `it,en,fr,fa`.

The side effect is that no language is actually filtered...

**Comment by MrPetovan** [comment]
I was hoping #11287 would provide a hint as of the why, but the issue seems to have self-resolved so I'm back to square one with this issue I haven't been able to reproduce.

**Comment by annando** [comment]
Fixed by https://github.com/friendica/friendica/pull/11422

**Comment by igor-cali** [comment]
@annando @ingoj Issue still present with '2022.05-rc', on Nerdica pod.

**Comment by igor-cali** [comment]
> @annando @ingoj Issue still present with '2022.05-rc', on Nerdica pod.

Issue fixed with '2022.06', on Nerdica pod.
