### ISSUE TITLE
[frio] Can't open Contacts > Groups > Individual Group

### ISSUE THREAD

**Issue by foss-** [friendica/friendica#12163]
This is Friendica, version 2022.12-dev that is running at the web location https://pirati.ca. The database version is 1489/1488, the post update version is 1484/1484.

When on `Contacts > Groups` clicking an individual group does not open the group view listing the groups contacts (stable). On dev a broken view is shown instead, e.g.:

![dev](https://user-images.githubusercontent.com/5708172/201472432-0c668e58-5eeb-4507-9f98-22e8a4a0ee74.png)

2022.09-rc OK
2022.12-dev NOT OK

**Comment by MrPetovan** [comment]
I am able to on 2022.12-dev. Can I ask you how many contacts you're following? These pages load your entire list of contacts so that you can add them one by one into the group. Too many contacts might break this page.

**Comment by foss-** [comment]
Bit over 100, don't think that is the issue.

**Comment by MrPetovan** [comment]
I don't think so either, but something is crashing the page after the beginning of the template is computed but before the list of contacts shows. I expect it to show in either the PHP log or the Friendica log.

**Comment by MrPetovan** [comment]
Possibly related to https://github.com/friendica/friendica/issues/11992#issuecomment-1327030221 that I fixed today in https://github.com/friendica/friendica/pull/12276

**Comment by foss-** [comment]
So far persisting, if the change is live on pirati.ca this is not resolved.

**Comment by annando** [comment]
I can confirm that. Sadly I had got no time so far to take a deeper look at it.

**Comment by MrPetovan** [comment]
This bug should leave a pretty obvious trace in the logs at the Error level if you have time to peruse.

**Comment by dpoulson** [comment]
I'm running latest dev (as of yesterday) and here is the error I'm getting in the logs: 

```
TypeError: Cannot access offset of type string on string in /home/droidbui/fr.droidbuilders.uk/view/smarty3/compiled/68/2e/5f/682e5f27069be016e288b2ee22760ad45e8c8413_2.file.entry.tpl.php:151
Stack trace:
#0 /home/droidbui/fr.droidbuilders.uk/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_638802fccefd41_06039905()
#1 /home/droidbui/fr.droidbuilders.uk/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#2 /home/droidbui/fr.droidbuilders.uk/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
#3 /home/droidbui/fr.droidbuilders.uk/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(385): Smarty_Internal_Template->render()
#4 /home/droidbui/fr.droidbuilders.uk/view/smarty3/compiled/41/ca/a2/41caa297e13abf1f7b000ab8814b59e497954280_2.file.groupeditor.tpl.php(36): Smarty_Internal_Template->_subTemplateRender()
#5 /home/droidbui/fr.droidbuilders.uk/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_6388c6474cc218_60306820()
#6 /home/droidbui/fr.droidbuilders.uk/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#7 /home/droidbui/fr.droidbuilders.uk/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
#8 /home/droidbui/fr.droidbuilders.uk/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(385): Smarty_Internal_Template->render()
#9 /home/droidbui/fr.droidbuilders.uk/view/smarty3/compiled/fc/ca/67/fcca67bacbd4bc2f364804f880112179617b8ad4_2.file.group_edit.tpl.php(100): Smarty_Internal_Template->_subTemplateRender()
#10 /home/droidbui/fr.droidbuilders.uk/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_6388c6474bef52_77052691()
#11 /home/droidbui/fr.droidbuilders.uk/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#12 /home/droidbui/fr.droidbuilders.uk/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
#13 /home/droidbui/fr.droidbuilders.uk/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render()
#14 /home/droidbui/fr.droidbuilders.uk/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute()
#15 /home/droidbui/fr.droidbuilders.uk/src/Render/FriendicaSmartyEngine.php(100): Smarty_Internal_TemplateBase->fetch()
#16 /home/droidbui/fr.droidbuilders.uk/src/Core/Renderer.php(84): Friendica\Render\FriendicaSmartyEngine->replaceMacros()
#17 /home/droidbui/fr.droidbuilders.uk/src/Module/Group.php(364): Friendica\Core\Renderer::replaceMacros()
#18 /home/droidbui/fr.droidbuilders.uk/src/BaseModule.php(244): Friendica\Module\Group->content()
#19 /home/droidbui/fr.droidbuilders.uk/src/App.php(738): Friendica\BaseModule->run()
#20 /home/droidbui/fr.droidbuilders.uk/index.php(44): Friendica\App->runFrontend()
#21 {main}
```

**Comment by dpoulson** [comment]
This is happening on my test account on my own instance, with just two contacts in total.

**Comment by MrPetovan** [comment]
Thank you, what theme(s) are you using?

**Comment by dpoulson** [comment]
Frio. 

Just checked Vier and can't replicate the error there.

**Comment by foss-** [comment]
Verified on Friendica, version 2022.12-dev that is running at the web location https://pirati.ca. The database version is 1496/1496, the post update version is 1484/1484.

Thanks so much @MrPetovan 🌿

**Comment by MrPetovan** [comment]
Since I couldn't reproduce the error, I wouldn't have be able to do much without the tireless work of @copiis and @dpoulson who reported the error messages from their log.
