### ISSUE TITLE
[fancybox] Only first column images open in gallery in new image grid feature

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#12413]
Cc @Brockhaus

It looks like the regular expression to convert image links into fancybox links needs a little refreshing.

See new HTML structure:
```html
<div class="body-attach">
    <div class="imagegrid-row">
        <div class="imagegrid-column">
            <a data-fancybox="gallery-5724515" href="https://assets.octodon.social/media_attachments/files/109/512/296/890/230/132/original/57a6dd180ce4497a.jpeg"><img src="https://friendica.mrpetovan.com/photo/preview/1024/1383174" alt="" title=""></a>
            <a data-fancybox="gallery-5724515" href="https://assets.octodon.social/media_attachments/files/109/512/297/946/698/483/original/832c389a153309f3.jpeg"><img src="https://friendica.mrpetovan.com/photo/preview/1024/1383178" alt="" title=""></a>
        </div>
        <div class="imagegrid-column">
            <a href="https://assets.octodon.social/media_attachments/files/109/512/297/675/803/637/original/856357284e1d3c96.jpeg"><img src="https://friendica.mrpetovan.com/photo/preview/1024/1383176" alt="" title=""></a>
            <a href="https://assets.octodon.social/media_attachments/files/109/512/298/029/857/032/original/32b418a50cd25b19.jpeg"><img src="https://friendica.mrpetovan.com/photo/preview/1024/1383180" alt="" title=""></a>
        </div>
    </div>
    <div class="clear"></div>
</div>
```

**Comment by brockhaus** [comment]
Well, as this is a future version of friendica I don't have installed, this is hard to test for me. But I see the problem.. ;)

Maybe my second pattern `#<div class="body-attach">.*?</div>#s` should be enhanced to `#<div class="(body-attach|imagegrid-column)">.*?</div>#s` right? This should be enough or am I overseeing something?

**Comment by brockhaus** [comment]
Or simply the dirty way.. :laughing: 
`#<div class="body-attach">.*?<div class="clear">#s`

**Comment by MarekBenjamin** [comment]
Just tell me when there is something to change in `image-grid.tpl`. Funny thing is that I do not encounter the problem, perhaps it depends on the browser? 
When I test image grind with fancybox on my dev instance, it works flawlessly:

https://friendica-dev.mbbit.de/display/fa8fe840-4063-960d-3c4c-053223776313

You should be able to test it there by yourself?

**Comment by MrPetovan** [comment]
This `<div class="clear">` element doesn't have any reason to exist anymore, so I would go with `#<div class="(body-attach|imagegrid-column)">.*?</div>#s` instead.

**Comment by MarekBenjamin** [comment]
@brockhaus do you want to take care of it or should I? You seem to be more familiar with DOM things 👼

**Comment by brockhaus** [comment]
> You should be able to test it there by yourself?
How should I test changes to my addon there? I am not allowed to install there, am I? :D

And the reason why it works for you: These images are post inline images. They are handled different by my addon then attached images.

**Comment by brockhaus** [comment]
> do you want to take care of it or should I? You seem to be more familiar with DOM things angel

I think it should be fixed inside the fancybox plugin.. But I do have to do it "blind", so I will put it on my repository first and hope, someone will test it with the new friendica version supporting the imagegrid.

**Comment by MarekBenjamin** [comment]
> And the reason why it works for you: These images are post inline images. They are handled different by my addon then attached images.

Ahh, I still don't get the technical meaning of "attached". I think that attached just means that the images are at the end of the post. But it has to mean something different, which I just did not figured out yet.

In any way, thank you very much, fixing it!

**Comment by brockhaus** [comment]
> Ahh, I still don't get the technical meaning of "attached".

The inline images you produce are done when editing posts inside of friendica mainly. But the more often way is, that posts have text only and images that are attached to it. This is how mastodon does it and with it most (if not all) mobile clients. 
So if you see posts created on mastodon, images of that posts are attached. They produce different HTML code in Friendica than your inline images.

**Comment by brockhaus** [comment]
Okay, I added the new pattern to fancybox. It is pushed to my own repo for now (https://codeberg.org/brockhaus/friendica-addons/src/branch/main/fancybox)
It is working with inline and attached images of current friendica still. Is someone able to test it with the new imagegrid feature (on attached images mainly)? If that works I'll do a PR.

**Comment by MarekBenjamin** [comment]
@brockhaus thank you so much for clarifying that to me. And based on this explanation, I really understand my previous confusion.
But still I was not able to encounter the problem even with post from mastodon, for what ever reason. 🤣 But never mind! Thank you for fixing it! 👼

**Comment by brockhaus** [comment]
@MrPetovan This is the wrong repository for that issue, right? I opened a PR in the correct one, "fixing" this issue. :)

**Comment by MrPetovan** [comment]
All Friendica issues including official addons are centralized in `friendica/friendica`, but addon PRs still need to be opened in `friendica/friendica-addons`.

**Comment by MrPetovan** [comment]
Closed by https://github.com/friendica/friendica-addons/pull/1335

**Comment by brockhaus** [comment]
@MrPetovan My fork is still one commit ahead.. Did you merge this in develop branch too, or into 2022.12 only?

**Comment by MrPetovan** [comment]
Currently we're working on the `2022.12-rc` branch, both on friendica and addons. After the release, we'll resume working on the `develop` branch. Until then, anything in the `develop` branch will not be released at the end of the month.

**Comment by brockhaus** [comment]
So I will do another PR then or is `2022.12-rc` merged into develop later?

Isn't it more common to work on `development` and merge features from there to the `2022-12-rc` branch we want to have in the upcoming release?

**Comment by MrPetovan** [comment]
I changed the base branch for the merge in your PR from `develop` to `2022.12-rc` from GitHub.

> Isn't it more common to work on `development` and merge features from there to the `2022-12-rc` branch we want to have in the upcoming release?

No, the purpose of this double branch is to add new features in the `develop` branch because we don't have time to properly test them before the release. But all other PRs should be pointing at the RC branch during the RC period.
