### ISSUE TITLE
[ActivityPub C2S] No activities in the inbox

### ISSUE THREAD

**Issue by yvolk** [friendica/friendica#12775]
- [X] I have searched open and closed issues for duplicates

### Bug Description

"inbox" is empty although I do see recent activity via Web UI.

The same reported earlier in https://github.com/andstatus/andstatus/issues/573#issuecomment-1417559818 

### Steps to Reproduce

1. I'm testing ActivityPub C2S API of Friendica using AndStatus app (the latest build is here: https://github.com/andstatus/andstatus/issues/456)

2. Via Web UI at https://pirati.ca/profile/andstatus/conversations I see recent activity:
(See "Received it, thanks!" reply)
![image](https://user-images.githubusercontent.com/207716/216829378-3c8f1be9-eb78-4c4f-ab74-a7438fe0eb32.png)

3. I request "Home" timeline sync in AndStatus app.
URL: https://pirati.ca/inbox/andstatus,
account: andstatus@pirati.ca/ActivityPub, 
Actual Result:
```
Headers:,
[HTTP/1.1 200 OK],
date: [Sun, 05 Feb 2023 15:42:17 GMT],
server: [Apache],
expires: [Sun, 05 Feb 2023 15:47:17 GMT],
transfer-encoding: [chunked],
x-android-selected-protocol: [http/1.1],
x-android-response-source: [NETWORK 200],
x-android-received-millis: [1675611738486],
x-android-sent-millis: [1675611738367],
strict-transport-security: [max-age=31536000],
x-account-management-status: [none],
keep-alive: [timeout=5, max=100],
x-response-type: [json],
connection: [Keep-Alive],
content-type: [application/activity+json],
cache-control: [max-age=300]
```
and body:
```
{
  "@context": [
    "https:\/\/www.w3.org\/ns\/activitystreams",
    "https:\/\/w3id.org\/security\/v1",
    {
      "vcard": "http:\/\/www.w3.org\/2006\/vcard\/ns#",
      "dfrn": "http:\/\/purl.org\/macgirvin\/dfrn\/1.0\/",
      "diaspora": "https:\/\/diasporafoundation.org\/ns\/",
      "litepub": "http:\/\/litepub.social\/ns#",
      "toot": "http:\/\/joinmastodon.org\/ns#",
      "featured": {
        "@id": "toot:featured",
        "@type": "@id"
      },
      "schema": "http:\/\/schema.org#",
      "manuallyApprovesFollowers": "as:manuallyApprovesFollowers",
      "sensitive": "as:sensitive",
      "Hashtag": "as:Hashtag",
      "quoteUrl": "as:quoteUrl",
      "conversation": "ostatus:conversation",
      "directMessage": "litepub:directMessage",
      "discoverable": "toot:discoverable",
      "PropertyValue": "schema:PropertyValue",
      "value": "schema:value"
    }
  ],
  "id": "https:\/\/pirati.ca\/inbox\/andstatus?page=1",
  "type": "OrderedCollectionPage",
  "partOf": "https:\/\/pirati.ca\/inbox\/andstatus",
  "orderedItems": []
}
```

Expected Result:

At least the latest reply from t131t1@msdn.io should be in the inbox.

**Comment by annando** [comment]
Is this expected to be like `api/statuses/mentions`? And are the other endpoints working like expected?

**Comment by yvolk** [comment]
20 minutes later I see a post by Michael on the "Latest Activity" tab, but inbox via API is still empty.
![image](https://user-images.githubusercontent.com/207716/216830332-5fc47a71-5670-461e-92e1-f2feea693800.png)

**Comment by yvolk** [comment]
> Is this expected to be like `api/statuses/mentions`?

All activities that should be received by a client app, should be visible via "inbox": public posts by friends, mentions, private posts... 

> And are the other endpoints working like expected?

No :-( but that is another story. I better create separate issues for other problems.

**Comment by annando** [comment]
I guess that you can combine them here, since there not that much endpoints. Best would be - if possible - to just map the AP endpoints to the matching Mastodon/Twitter API endpoints.

**Comment by yvolk** [comment]
Of course, in AndStatus client app I'm mapping one "inbox" to all "usual" timelines like "Home", "Private", "Interactions" (similar to "Mentions"), etc.
So lack of Activities in the "inbox" means that there is nothing in ALL "incoming" timelines of the app.
I can only see some activities from "outbox" so far - this is "Sent" timeline in AndStatus (see the screenshot in https://github.com/andstatus/andstatus/issues/573#issuecomment-1417286215)

**Comment by yvolk** [comment]
BTW on that screenshot you can see "Home": this is because "my" messages are usually shown in "Home" timeline also (i.e. not only in "Sent"), although in C2S they were retrieved from "outbox" :-)

**Comment by annando** [comment]
I now fixed that problem, that one of the endpoints hadn't delivered data. But the problem persists, that the order appears totally random.

**Comment by yvolk** [comment]
@annando I see, why the order of Activities in AndStatus timeline is random. Because this is an order of activities, not of "Notes", etc. 
Looking into JSON we see that all "Activities" that were retrieved today, were "published" right now. As if a week old Note was published a second ago :-)

Does your system generate "fake" activities for "Notes" on the fly?

This bug may explain why AndStatus is greedy for you...

**Comment by annando** [comment]
We mostly don't store the original activities after we processed the content. I also now replaced the link to the actor with an actor object. so that AndStatus does have got all needed information. I now changed the origin of the date in the created object.

**Comment by yvolk** [comment]
Looks like works good so far.

> I also now replaced the link to the actor with an actor object. so that AndStatus does have got all needed information

This causes unneeded traffic, AndStatus should be able retrieving Actor's info by itself. See https://github.com/andstatus/andstatus/issues/563 which I thought I implemented :-)

BUT. The problem is that if an Actor is from some other host, AndStatus looks up the Actor at THAT host, naturally, using the provided URL. And that host may not provide the actor object in ActivityPub format by that URL... so looks like having Actor's objects at least for Actors of OTHER hosts is really needed, but is not necessary for actors of THIS host. Or maybe we shouldn't try to optimize this?!

**Comment by annando** [comment]
I currently reverted this change with the actors. Now I have got the issue that the timeline is fetched and display for the first time. But after this AndStatus still continues to fetch the data (according to the log) but doesn't display any new content. Also no avatars are displayed.

I'm thinking about adding a reduced set of fields to the actor as an array. So AndStatus wouldn't need to fetch avatar and username on their own. Something else: Are pictures fetched the same way as the API endpoints? Mean: With credentials?

**Comment by yvolk** [comment]
1. Regarding AndStatus fetching the same timeline data twice. Yesterday I noticed that two oldest pages were retrieved twice but didn't find out, why...
3. Images are fetched with authentication first. In a case of an error another attempt is made to get an image without authentication. This is a general pattern, I didn't look now specifically for OAuth 2.0...

**Comment by annando** [comment]
In that actor array I also replaced the original path to the avatar with a local path. This reduces load on the remote system and also improves the privacy.

Concerning the endpoints: There are currently three endpoints developed:
- `inbox/username` - The Timeline of the user with all posts from people that this user subscribed to
- `outbox/username` - all the posts written by the given user
- `inbox` - all posts that arrived on this system

Also I'm thinking about introducing the endpoint `outbox` that then would contain all posts by local users. Question is only how to advertise this endpoint. What do you think about this?

**Comment by yvolk** [comment]
> In that actor array I also replaced the original path to the avatar with a local path. This reduces load on the remote system and also improves the privacy.

A client app can get the Actor object not only from 
1. THIS one server (where one of accounts exists), but also:
2. Other ActivityPub servers, where OTHER accounts exist (AndStatus allows to have many accounts in the same ONE "ActivityPub")
3. Any other servers, from which it will retrieve additional info about "non-local" activities...

I think that in this case any substitutions of avatars, images in notes, etc. will only cause a confusion... :-(

> Concerning the endpoints...

Let's look into the spec: https://www.w3.org/TR/activitypub/#actor-objects
It mentions, in particular, these collections of activities (and maybe other "objects" also...):
* inbox
* outbox
* liked
* sharedInbox  (see about it also here: https://www.w3.org/TR/activitypub/#shared-inbox-delivery ) - this one, as I understand, contains both "all posts that arrived on this system" and public posts FROM local users.

**Comment by annando** [comment]
I still can't really use AndStatus in the C2S mode. At first it does seem to load content, but then it stops working and no new content is loaded. Only when I set up the connection for the first time, it does display new content.

**Comment by yvolk** [comment]
@annando I will investigate this and report here.

**Comment by yvolk** [comment]
> I still can't really use AndStatus in the C2S mode. At first it does seem to load content, but then it stops working and no new content is loaded. Only when I set up the connection for the first time, it does display new content.

Hello @annando At last I fixed this bug in AndStatus. Please check v.60.04 here: https://github.com/andstatus/andstatus/issues/456

Now during syncing AndStatus will start with the first page (in the absence of "prev" page link). As I see, for "andstatus" user at pirati.ca this will be "https://pirati.ca/inbox/andstatus?page=1".
This is not a very good solution to always request the whole first page, which may not have anything new, so in order to minimize traffic please implement "prev" property for a Collection Page. See section 4.6.1 "Collection Paging" https://www.w3.org/TR/activitystreams-core/#collections

Currently only "next" link is present pointing to the older activities, e.g.:
```
  "id": "https:\/\/pirati.ca\/inbox\/andstatus?page=1",
  "type": "OrderedCollectionPage",
  "next": "https:\/\/pirati.ca\/inbox\/andstatus?max_id=38162041",
  "partOf": "https:\/\/pirati.ca\/inbox\/andstatus",
  "orderedItems": [
     ...
```

**Comment by yvolk** [comment]
@annando Please note that if you upgrade from previous AndStatus version, in order to forget the wrong "prev" link you need to go to top menu -> Manage Timelines -> select Home timeline -> and click "Forget sync events and dates" in its context menu.
