### ISSUE TITLE
RSS Feed do not show Description

### ISSUE THREAD

**Issue by Mannshoch** [friendica/friendica#13290]
I added this RSS feed as Contact:
https://www.efk.admin.ch/de/publikationen/wirtschaft-verwaltung/informatikprojekte.feed?type=rss

I get this:
![grafik](https://github.com/friendica/friendica/assets/7795891/c1506e68-ef82-48fb-8c9c-16be685bf2fa)

But I assumed to get the Description:
```
<description>
<![CDATA[<p>E-ZIVI ist die zentrale Software-Fachanwendung für die Abwicklung der Vollzugsprozesse des Zivildienstes im Bundesamt für Zivildienst (ZIVI). Die Anwendung ist am Ende des Lebenszyklus angelangt und soll bis Ende 2024 abgelöst werden. Das ZIVI hat dazu ein Digitalisierungsprojekt zur Neuentwicklung der Fachanwendung gestartet. Die geschätzten Projektkosten belaufen sich auf insgesamt 13,3 Millionen Franken. Das Projekt wurde im Mai 2022 freigegeben und befindet sich zum Prüfungszeitpunkt in der Konzeptphase.</p>
<ul class="linkliste">
<li style="text-align: left;"><a href="https://www.efk.admin.ch/images/stories/efk_dokumente/publikationen/_wirtschaft_und_verwaltung/informatikprojekte/22452/22452BE-Endgueltige-Fassung-V04.pdf" target="_blank">Bericht</a></li>
<li style="text-align: left;"><a href="https://www.efk.admin.ch/images/stories/efk_dokumente/publikationen/_wirtschaft_und_verwaltung/informatikprojekte/22452/22452BE-WiK-d.pdf" target="_blank">Zusammenfassung</a></li>
</ul>]]>
</description>
```
Is it possible to set up the content friendica should show from the feed?

**Comment by MrPetovan** [comment]
Following the provided RSS feed, this is what I see:
<img width="375" alt="image" src="https://github.com/friendica/friendica/assets/925415/270adaf7-a4a5-4d81-81b5-84fb7bf161bc">
This matches the content of the `<description>` tag in the XML feed.

**Comment by Mannshoch** [comment]
Is there something to configure for me?

**Comment by MrPetovan** [comment]
No, this was tested out-of-the-box on the `develop` branch. Maybe your issue is already fixed in the upcoming 2023.09 version.

**Comment by Mannshoch** [comment]
Sorry no. The Problem still resides. The RSS shows still the title instead the description.
I use:
Friendica 'Yellow Archangel' 2023.12 - 1542

**Comment by annando** [comment]
What have you configured in 'Fetch further information for feeds' on the contact page?
