### ISSUE TITLE
Update with docker image 2023.09-rc fails startup

### ISSUE THREAD

**Issue by ne20002** [friendica/friendica#13699]
- [x] I have searched open and closed issues for duplicates

### Bug Description
```
Initializing Friendica 2023.09-rc ...

Upgrading Friendica from 2023.09-rc ...

Initializing finished

Upgrading Friendica ...



Deprecated: Return type of Friendica\Core\Session\Handler\Cache::read($id) should either be compatible with SessionHandlerInterface::read(string $id): string|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/src/Core/Session/Handler/Cache.php on line 49



Deprecated: Return type of Friendica\Core\Session\Handler\Cache::gc($max_lifetime): bool should either be compatible with SessionHandlerInterface::gc(int $max_lifetime): int|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/src/Core/Session/Handler/Cache.php on line 113



Warning: ini_set(): Session ini settings cannot be changed after headers have already been sent in /var/www/html/src/Core/Session/Type/Native.php on line 36



Warning: ini_set(): Session ini settings cannot be changed after headers have already been sent in /var/www/html/src/Core/Session/Type/Native.php on line 37



Warning: ini_set(): Session ini settings cannot be changed after headers have already been sent in /var/www/html/src/Core/Session/Type/Native.php on line 38



Warning: ini_set(): Session ini settings cannot be changed after headers have already been sent in /var/www/html/src/Core/Session/Type/Native.php on line 41



Warning: session_set_save_handler(): Session save handler cannot be changed after headers have already been sent in /var/www/html/src/Core/Session/Type/Native.php on line 45



Warning: session_start(): Session cannot be started after headers have already been sent in /var/www/html/src/Core/Session/Type/Native.php on line 54



Upgrading finished

[06-Dec-2023 13:30:26] NOTICE: fpm is running, pid 1

[06-Dec-2023 13:30:26] NOTICE: ready to handle connections

127.0.0.1 -  06/Dec/2023:13:30:41 +0100 "GET /index.php" 200

127.0.0.1 -  06/Dec/2023:13:30:41 +0100 "GET /index.php" 501

127.0.0.1 -  06/Dec/2023:13:30:41 +0100 "GET /index.php" 200
```

```

Deprecated: Return type of Friendica\Core\Session\Handler\Cache::read($id) should either be compatible with SessionHandlerInterface::read(string $id): string|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/src/Core/Session/Handler/Cache.php on line 49

Deprecated: Return type of Friendica\Core\Session\Handler\Cache::gc($max_lifetime): bool should either be compatible with SessionHandlerInterface::gc(int $max_lifetime): int|false, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/html/src/Core/Session/Handler/Cache.php on line 113

Warning: ini_set(): Session ini settings cannot be changed after headers have already been sent in /var/www/html/src/Core/Session/Type/Native.php on line 36

Warning: ini_set(): Session ini settings cannot be changed after headers have already been sent in /var/www/html/src/Core/Session/Type/Native.php on line 37

Warning: ini_set(): Session ini settings cannot be changed after headers have already been sent in /var/www/html/src/Core/Session/Type/Native.php on line 38

Warning: ini_set(): Session ini settings cannot be changed after headers have already been sent in /var/www/html/src/Core/Session/Type/Native.php on line 41

Warning: session_set_save_handler(): Session save handler cannot be changed after headers have already been sent in /var/www/html/src/Core/Session/Type/Native.php on line 45

Warning: session_start(): Session cannot be started after headers have already been sent in /var/www/html/src/Core/Session/Type/Native.php on line 54

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/src/Core/Session/Handler/Cache.php:31) in /var/www/html/src/App.php on line 638

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/src/Core/Session/Handler/Cache.php:31) in /var/www/html/src/App.php on line 703

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/src/Core/Session/Handler/Cache.php:31) in /var/www/html/src/Model/User/Cookie.php on line 179

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/src/Core/Session/Handler/Cache.php:31) in /var/www/html/src/Security/Authentication.php on line 80

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/src/Core/Session/Handler/Cache.php:31) in /var/www/html/src/Core/System.php on line 531

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/src/Core/Session/Handler/Cache.php:31) in /var/www/html/src/Core/System.php on line 294

Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/src/Core/Session/Handler/Cache.php:31) in /var/www/html/src/Core/System.php on line 307

```

### Steps to Reproduce

Update with docker image 2023.09-rc

Actual Result:

Errors on startup, can't log in.

Expected Result:

It's an RC.

### Platform Info

Friendica Version: 2023.09-rc

Friendica Source: docker image

**Comment by ne20002** [comment]
Tusky is still working, but web interface is broken.

**Comment by MrPetovan** [comment]
None of these are showstoppers, what's this lone 501 error though?

**Comment by ne20002** [comment]
I updated the 2023.09-rc image and restarted the pod. 
* This is console output and messages after trying to log in via web browser
* Tusky is working, except pictures can't be loaded/shown. It's always blurred.

I will try to get a deeper look tomorrow.

**Comment by ne20002** [comment]
Hi @MrPetovan 

I fixed it by going back to the last image version. It's always good to have a backup.

* current docker image 2023.09-rc-fpm (with php 8.1) shows this error
* last docker image 2023.09-rc-fpm (with php 8.0) works ok 

I replaced the php 8.1 version with the php 8.0 version -> all ok
I again updated the image and started the php 8.1 version -> same problem
I again replaced the image with the php 8.0 version -> all ok.

**Comment by MrPetovan** [comment]
Thank you for the report, we are several admins running PHP version 8.2, so I'm surprised you're having trouble specifically with PHP 8,1.

**Comment by ne20002** [comment]
Maybe a problem with the image? Or something to update on the Nginx?

**Comment by MrPetovan** [comment]
Without any more error messages, there's little I can say about this. I've addressed the Deprecated messages which may or may not solve the issue.

Maybe it's just that the message display is tripping the return headers and foiling the UI. I've submitted a patch addressing these.

**Comment by ne20002** [comment]
Nope, it is still happening.

Found this as last entry in friendica.log:
```
2023-12-07T14:51:42Z app [ERROR]: Uncaught Exception TypeError: "Unsupported operand types: array + null" at /var/www/html/src/Core/Session/Type/AbstractSession.php line 82 {"exception":"TypeError: Unsupported operand types: array + null in /var/www/html/src/Core/Session/Type/AbstractSession.php:82\nStack trace:\n#0 /var/www/html/src/Core/Session/Model/UserSession.php(199): Friendica\\Core\\Session\\Type\\AbstractSession->setMultiple(Array)\n#1 /var/www/html/src/Model/Profile.php(822): Friendica\\Core\\Session\\Model\\UserSession->setMultiple(Array)\n#2 /var/www/html/src/App.php(599): Friendica\\Model\\Profile::addVisitorCookieForHandle('https://social....')\n#3 /var/www/html/index.php(55): Friendica\\App->runFrontend(Object(Friendica\\App\\Router), Object(Friendica\\Core\\PConfig\\Type\\JitPConfig), Object(Friendica\\Security\\Authentication), Object(Friendica\\App\\Page), Object(Friendica\\Content\\Nav), Object(Friendica\\Module\\Special\\HTTPException), Object(Friendica\\Util\\HTTPInputData), 1701960702.7951, Array)\n#4 {main}"} - {"file":null,"line":null,"function":null,"request-id":"6571dbfec2985","stack":"ErrorHandler::handleException (128), ErrorHandler::Friendica\\Core\\Logger\\Handler\\{closure}","uid":"c96f43","process_id":117}
```

**Comment by haheute** [comment]
I just tried to change from php 8.1 to php 8.2 and had a similar error. (`Unsupported operand types: array + null`)
The page was white. It seemed I had to install the `php82-session` package.. (or maybe just `php-session` in your distro)

edit: I don't know how this works with docker. just wanted to add the info , maybe it helps

edit2: maybe @nupplaphil knows

**Comment by MrPetovan** [comment]
Ah, this error I can look into.

**Comment by ne20002** [comment]
Thank you very much. Now Friendica starts with latest docker image (php version 8.1.26), but it's not done. :(

Within the log I find the following:

```
E_WARNING: Cannot modify header information - headers already sent by (output started at /var/www/html/vendor/patrickschur/language-detection/src/LanguageDetection/LanguageResult.php:15)
```

```
E_DEPRECATED: Return type of LanguageDetection\LanguageResult::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
```

Selecting Admin -> Federation I get page with errors (multiple):
```
Deprecated: number_format(): Passing null to parameter #1 ($num) of type float is deprecated in /var/www/html/src/Module/Admin/Federation.php on line 188

Deprecated: Implicit conversion from float 134.14473684210526 to int loses precision in /var/www/html/src/Core/L10n.php on line 317
```
All other pages seem to be ok. :)

**Comment by MrPetovan** [comment]
> ```
> E_WARNING: Cannot modify header information - headers already sent by (output started at /var/www/html/vendor/patrickschur/language-detection/src/LanguageDetection/LanguageResult.php:15)
> ```
> 
> ```
> E_DEPRECATED: Return type of LanguageDetection\LanguageResult::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
> ```

This can be fixed by raising the minimum PHP version to 7.4, which I believe is fine.

**Comment by ne20002** [comment]
I can confirm that the warnings in Adminstration / Federation Statistics are now gone.

**Comment by MrPetovan** [comment]
And I'm planning on raising the minimum PHP version at the same time I update all the PHP dependencies closer to the release date, which will suppress the deprecation notices in `LanguageDetection`.

**Comment by ne20002** [comment]
@MrPetovan:
I can confirm that with latest version (as of today) the deprecation warnings have been gone. 👍 

For the context:

![grafik](https://github.com/friendica/friendica/assets/39007279/d3b339f6-8d7d-4a14-ac6e-e9fb4e1a175b)
