### ISSUE TITLE
Posts are not delivered

### ISSUE THREAD

**Issue by atasingorneq** [friendica/friendica#14125]
- [x] I have searched open and closed issues for duplicates

### Bug Description

Newly created posts are no longer delivered since the last pull request.

### Steps to Reproduce

1.  Create a post
2.  Click on submit

Actual Result:

The hourglass symbol remains and the post is not delivered.

Expected Result:

The post is delivered

### Troubleshooting

1. Deactivate the Bluesky addon or undo the last pull request
2. Now edit the unsent posts and they will be sent.

The error is probably caused by the Bluesky add-on.

Here is the discussion on this error: [https://libranet.de/display/0b6b25a8-6366-3266-9309-f60370327494](https://libranet.de/display/0b6b25a8-6366-3266-9309-f60370327494)

### Platform Info

Friendica Version: 'Yellow Archangel' 2024.06-dev - 1560

Friendica Source: git

PHP version: 8.2.18

**Comment by AlfredSK** [comment]
It's a bug introduced with the last PR for the bluesky addon. Either deactivate it or revert the last commits to the addon repo locally on your node.

See this PR and my comment... https://git.friendi.ca/friendica/friendica-addons/pulls/1499#issuecomment-185479

**Comment by AlfredSK** [comment]
I guess this is the corresponding error:

```
app [ERROR]: Uncaught Exception TypeError: "bluesky_get_did(): Argument #1 ($handle) must be of type string, null given, called in .../addon/bluesky/bluesky.php on line 1780" at .../addon/bluesky/bluesky.php line 1749 
{"exception":"TypeError: bluesky_get_did(): Argument #1 ($handle) must be of type string, null given, called in .../addon/bluesky/bluesky.php on line 1780 and defined in .../addon/bluesky/bluesky.php:1749
Stack trace:
#0 .../addon/bluesky/bluesky.php(1780): bluesky_get_did()
#1 .../addon/bluesky/bluesky.php(100): bluesky_get_user_did()
#2 .../src/Core/Hook.php(222): bluesky_check_item_notification()
#3 .../src/Core/Hook.php(198): Friendica\\Core\\Hook::callSingle()
#4 .../src/Model/Post/UserNotification.php(416): Friendica\\Core\\Hook::callAll()
#5 .../src/Model/Post/UserNotification.php(231): Friendica\\Model\\Post\\UserNotification::getProfileForUser()
#6 .../src/Model/Post/UserNotification.php(170): Friendica\\Model\\Post\\UserNotification::setNotificationForUser()
#7 .../src/Model/Item.php(1383): Friendica\\Model\\Post\\UserNotification::setNotification()
#8 .../src/Model/Item.php(1957): Friendica\\Model\\Item::insert()
#9 .../src/Model/Item.php(1750): Friendica\\Model\\Item::storeForUser()
#10 .../src/Protocol/Diaspora.php(1878): Friendica\\Model\\Item::distribute()
#11 .../src/Protocol/Diaspora.php(581): Friendica\\Protocol\\Diaspora::receiveLike()
#12 .../src/Protocol/Diaspora.php(514): Friendica\\Protocol\\Diaspora::dispatch()
#13 .../src/Module/Diaspora/Receive.php(82): Friendica\\Protocol\\Diaspora::dispatchPublic()
#14 .../src/Module/Diaspora/Receive.php(61): Friendica\\Module\\Diaspora\\Receive->receivePublic()
#15 .../src/BaseModule.php(233): Friendica\\Module\\Diaspora\\Receive->post()
#16 .../src/App.php(714): Friendica\\BaseModule->run()
#17 .../index.php(55): Friendica\\App->runFrontend()
#18 {main}"} - 
{"file":null,"line":null,"function":null,"request-id":"6632676708ed4","stack":"ErrorHandler::handleException (128), ErrorHandler::Friendica\\Core\\Logger\\Handler\\{closure}","uid":"4a6c9b","process_id":1666393}```

**Comment by MrPetovan** [comment]
Fixed in https://git.friendi.ca/friendica/friendica-addons/pulls/1501

**Comment by AlfredSK** [comment]
Hmm. I pulled the updated code but still have the same issue. The delivery indicator is showing the empty hour glass forever. The notifier task doesn't seem to be executed.

**Comment by annando** [comment]
I applied some more changes. With the latest code in the addons it should now work again.

**Comment by AlfredSK** [comment]
I'm pretty busy at the moment. But I'll try later today.

**Comment by AlfredSK** [comment]
Now it seems to work reliably. :-) Thanks!

**Comment by annando** [comment]
Sorry for the problems!
