### ISSUE TITLE
Comments of pending contacts won't show up in the network stream

### ISSUE THREAD

**Issue by rabuzarus** [friendica/friendica#2772]
If user 1 gets a connection request from user 2 and he/she doesn't accept this request the public comments of user 2 (e.g. forum comments) are not visible anymore in the network stream of user 1.

Some investigations to solve this have been already done. The following line in the query of `function item_joins()` (https://github.com/friendica/friendica/blob/develop/include/conversation.php#L444) needs to be changed to `NOT (`contact`.`blocked` AND NOT `contact`.`pending`)`
But pending contacts are still marked as `not writeable` in the `contact` table. So it wouldn't be possible to comment to an item of a pending contact.
We need to solve this.

**Comment by annando** [comment]
I think we should solve this in the next release. There are some issues with the thread stuff that we need to have solved.

**Comment by rabuzarus** [comment]
The fix isn't working. I have tested this and the comments of pending contacts are still not displayed. See https://github.com/friendica/friendica/pull/2952#issuecomment-262075873 for explanation

**Comment by tobiasd** [comment]
Is it now working?

**Comment by rabuzarus** [comment]
seems so. I think we can close it know.
