### ISSUE TITLE
Every Quote destroys my layout. Need your help!

### ISSUE THREAD

**Issue by Nachtwesen** [friendica/friendica#3052]
Hi! Sorry, I have a problem that makes me nearby unable to use friendica :(.

Dosn´t matter whitch layout I try (tryed all in package), every quote of an user destroys it.

Look at my example. Its every time the same:
![friendica3](https://cloud.githubusercontent.com/assets/1521445/21525643/ed3805a6-cd1e-11e6-8c71-abdedd619f12.gif)

After the "Teilen"-Link at the end of the first post, table (div???) gets NOT closed. So the next posting appears IN(!) the same table(?). If I scroll down and more quotes appears it gets destroyed even more.

Clear friendica 3.5 installation without AddOns (tested it without anyone!). On every theme and with every quote (from Friedica or Diaspora eg dosn´t matter). Everything else works fine, installation shows green on all requirements.

Please somebody can help? Thank you!

**Comment by rabuzarus** [comment]
This is fixed in the actual develop branch. See https://github.com/friendica/friendica/commit/b0a0cf94e4ded2a19acc40d4588fede6b73f3615

You can switch to the develop branch or you need to wait until the next stable release (friendica 3.5.1)

**Comment by Nachtwesen** [comment]
@rabuzarus Thank you for your answer. I added the missing / in shared_content.tpl, but problem is not solved :(. I deleted cache and reload the layout in settings. There is another place I have to edit? Thanks again.

**Comment by rabuzarus** [comment]
I guess it will only work for new posts. Friendica transmit the messages as bbcode. If a message arrive on your instance your friendica instance will check the bbcode and will transform it to hmtl. We store a cached version of this html in the db (along with the original bbcode) for performance reasons (otherwise we would have to run the transformation process every time on page refresh). 
The template you have edited is used for the transformation process to html but your post is already stored so it would only work for new posts

If you really want to change this for old posts you have to step in to the `item` table of your db. There you to identify your post and have to delete the field for cached html. In this case friendica would try run the transformation process again for this post

**Comment by Nachtwesen** [comment]
@rabuzarus Thank you again. Thats ok with the old posts. So I have to wait on new posts to see if it works :). I would be so happy if it was solved, because I love Friendica.

**Comment by Nachtwesen** [comment]
Seems to work. I am so happy :))

**Comment by rabuzarus** [comment]
Cool :-)

Can we close this issue?

**Comment by Nachtwesen** [comment]
Jep, it works fine :). Can be closed. Thanks.
