### ISSUE TITLE
Firefox v64+: Long lines of code content don't wrap

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#3837]
If you use the markup [code][/code] it produces a very ugly output because it doesn't do wordwrap. I understand that it would break the concept, but this looks like the page has an error. So maybe add scrollbars to such an element.
![00temp](https://user-images.githubusercontent.com/24474762/32168247-15000eec-bd6c-11e7-8520-cd78fcd83eaa.png)

**Comment by tobiasd** [comment]
Is this still an issue or was it fixes along the war? I've just created a private note to test this and the very long lines of code were wrapped around when the column with of the content column in frio was reached.

**Comment by MrPetovan** [comment]
Did you add any space in your very long line of code? The provided example has none.

**Comment by tobiasd** [comment]
But even without a space and only a long line of gibberish in the code block it is wrapped around at the end of the line for me in vier and frio.

**Comment by hoergen** [comment]
Fixed here too ! 👍

**Comment by MrPetovan** [comment]
Long lines still don't wrap in Firefox version 64+

Forum post: https://forum.friendi.ca/display/ec054ce7-145c-7146-993f-02b666345884
Test page: https://pirati.ca/display/cd9f100a-155c-707c-7db5-88f746309358

**Comment by nupplaphil** [comment]
fixed with #6793
