### ISSUE TITLE
"Like" messages are shown on the community page - pls remove

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#4251]
On the community page there are "like" messages that are useless at least on that page. Can we remove this? Likes coming from friendica and OStatus.
Wrote that already in Friendicas support forum, but thought opening an issue on that maybe the better way ;)
![00_temp](https://user-images.githubusercontent.com/24474762/34962969-6bbbb530-fa46-11e7-976d-4c40b2569d6c.png)

**Comment by annando** [comment]
Should not happen anymore.

**Comment by MrPetovan** [comment]
What was the PR that fixed this?

**Comment by annando** [comment]
The public commenting. That changed the way that the items are generated.

**Comment by MrPetovan** [comment]
@AlfredSK is correct! I like linking issues with pull requests on GitHub.

**Comment by annando** [comment]
It belongs to the package of pull request that are collected under the issue https://github.com/friendica/friendica/issues/4117

**Comment by tobiasd** [comment]
Is it listed there as known problem that needs to be fixed?

**Comment by annando** [comment]
It should have been fixed as a side effect to the linked issue.

**Comment by hoergen** [comment]
It's not fixed on the network/new page. Is still can see a lot "Horst likes Schantalles Schampus" ;)

**Comment by tobiasd** [comment]
But initially the issue was about the community page ;-)

**Comment by hoergen** [comment]
You want me to open a new issue?

**Comment by MrPetovan** [comment]
Yes please, as they are different pages.
