### ISSUE TITLE
Communication problem between nodes

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#4309]
I post this issue here because it seems that communication or delivery between nodes is broken.
I sent some post and comments to the support forum. Nothing arrived there. I also commented one of the threads directly as the support-forum-user. No success.
Maybe this started with the changes to RINO/encryption between nodes. But I'm not sure.
I cannot provide any additional information now. It's late. I have to sleep now. Sorry.

**Comment by AlfredSK** [comment]
Also, the worker queue is quite long. Unusual long. On both nodes (libranet.de and forum.friendi.ca)

**Comment by annando** [comment]
This is solved by PR https://github.com/friendica/friendica/pull/4310

**Comment by MrPetovan** [comment]
I have had performances issues as well after setting the RINO value to 1.

**Comment by annando** [comment]
Is it solved now?

**Comment by zeroadam** [comment]
I am still unable to communicate with @MrPetovan, but everything else seems great!

**Comment by MrPetovan** [comment]
I'm special.

**Comment by zeroadam** [comment]
Is that good special, or bad special? 😆

**Comment by MrPetovan** [comment]
Apparently it's especially bad.

**Comment by AlfredSK** [comment]
The queue looks like this now:
Message queues 165 - 0 (forum.friendi.ca) and 361 - 1 (libranet.de)
So, the workers queue (?) is back to normal.
The queue of outgoing messages is still higher than usual. Need to check the log for errors. Will report later.

**Comment by zeroadam** [comment]
I don't know if it's related or will help @MrPetovan , but the magic link when I visit you **never** works. I've been checking my other contacts and they all seem to work, even @AlfredSK . So I thought I'd mention it.

**Comment by AlfredSK** [comment]
I checked the queues of both instances. Most of the servers in the queue are in fact not reachable (404, timeout, whatever). The problem has vanished, I guess. Hooray! 🎉 
May I close it?

**Comment by MrPetovan** [comment]
Of course!

**Comment by AlfredSK** [comment]
Closing....

**Comment by MrPetovan** [comment]
Successfully closed!

**Comment by AlfredSK** [comment]
Indeed. 😃
