### ISSUE TITLE
Mastodon: Support Sensitive Content flag image feature

### ISSUE THREAD

**Issue by MrPetovan** [friendica/friendica#4414]
We already are [supporting Mastodon's Content Warning hiding feature](https://github.com/friendica/friendica/issues/3285), but images flagged as Sensitive Content still get displayed in full in Friendica.

Mastodon side (safe): https://octodon.social/@kingu_platypus_gidora/99485066158302598
Friendica side (NSFW): https://friendica.mrpetovan.com/display/3ad700c49a85fb0aef6b3da0ae051d87cfe9b401

**Comment by annando** [comment]
Have you more information how the content is marked as sensitive?

**Comment by MrPetovan** [comment]
Not yet, since I'm at work. I'll look more into it hopefully tonight.

**Comment by MrPetovan** [comment]
Item source:
````xml
<?xml version="1.0"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:thr="http://purl.org/syndication/thread/1.0" xmlns:activity="http://activitystrea.ms/spec/1.0/" xmlns:poco="http://portablecontacts.net/spec/1.0" xmlns:media="http://purl.org/syndication/atommedia" xmlns:ostatus="http://ostatus.org/schema/1.0" xmlns:mastodon="http://mastodon.social/schema/1.0">
  <id>https://octodon.social/users/kingu_platypus_gidora.atom</id>
  <title>Anarkingu Gidora</title>
  <subtitle>Hello World! I am Kingu
D*: https://diasp.org/people/37b279f2a9f2348d
Music: https://kingu.reactoweb.com/</subtitle>
  <updated>2018-01-16T14:46:13Z</updated>
  <logo>https://assets.octodon.social/accounts/avatars/000/001/586/original/dc4b91f65bcc95d6.gif</logo>
  <author>
    <id>https://octodon.social/users/kingu_platypus_gidora</id>
    <activity:object-type>http://activitystrea.ms/schema/1.0/person</activity:object-type>
    <uri>https://octodon.social/users/kingu_platypus_gidora</uri>
    <name>kingu_platypus_gidora</name>
    <email>kingu_platypus_gidora@octodon.social</email>
    <summary type="html">&lt;p&gt;Hello World! I am Kingu&lt;br /&gt;D*: &lt;a href="https://diasp.org/people/37b279f2a9f2348d" rel="nofollow noopener" target="_blank"&gt;&lt;span class="invisible"&gt;https://&lt;/span&gt;&lt;span class="ellipsis"&gt;diasp.org/people/37b279f2a9f23&lt;/span&gt;&lt;span class="invisible"&gt;48d&lt;/span&gt;&lt;/a&gt;&lt;br /&gt;Music: &lt;a href="https://kingu.reactoweb.com/" rel="nofollow noopener" target="_blank"&gt;&lt;span class="invisible"&gt;https://&lt;/span&gt;&lt;span class=""&gt;kingu.reactoweb.com/&lt;/span&gt;&lt;span class="invisible"&gt;&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;</summary>
    <link rel="alternate" type="text/html" href="https://octodon.social/@kingu_platypus_gidora"/>
    <link rel="avatar" type="image/gif" media:width="120" media:height="120" href="https://assets.octodon.social/accounts/avatars/000/001/586/original/dc4b91f65bcc95d6.gif"/>
    <link rel="header" type="image/jpeg" media:width="700" media:height="335" href="https://assets.octodon.social/accounts/headers/000/001/586/original/488457a59ee3a63f.jpg"/>
    <poco:preferredUsername>kingu_platypus_gidora</poco:preferredUsername>
    <poco:displayName>Anarkingu Gidora</poco:displayName>
    <poco:note>Hello World! I am Kingu
D*: https://diasp.org/people/37b279f2a9f2348d
Music: https://kingu.reactoweb.com/</poco:note>
    <mastodon:scope>public</mastodon:scope>
  </author>
  <link rel="alternate" type="text/html" href="https://octodon.social/@kingu_platypus_gidora"/>
  <link rel="self" type="application/atom+xml" href="https://octodon.social/users/kingu_platypus_gidora.atom"/>
  <link rel="hub" href="https://octodon.social/api/push"/>
  <link rel="salmon" href="https://octodon.social/api/salmon/1586"/>
  <entry>
    <id>https://octodon.social/users/kingu_platypus_gidora/statuses/99485066158302598</id>
    <published>2018-02-07T16:40:39Z</published>
    <updated>2018-02-07T16:40:39Z</updated>
    <title>New status by kingu_platypus_gidora</title>
    <activity:object-type>http://activitystrea.ms/schema/1.0/note</activity:object-type>
    <activity:verb>http://activitystrea.ms/schema/1.0/post</activity:verb>
    <link rel="alternate" type="application/activity+json" href="https://octodon.social/users/kingu_platypus_gidora/statuses/99485066158302598"/>
    <content type="html" xml:lang="en">&lt;p&gt;Sometime like 6 months ago I followed the page of a Japanese Idol band name Kamen Joshi. They pretend to be Ska idol and all wear masks to hide their identity.&lt;/p&gt;&lt;p&gt;I thought the concept was cool.&lt;/p&gt;&lt;p&gt;Then, later, they started posting pics without mask&lt;/p&gt;&lt;p&gt;Then,  later again, they started posting bikini pics&lt;/p&gt;&lt;p&gt;Then, later again, they started posting picture in underwear&lt;/p&gt;&lt;p&gt;I am expecting porn soon...&lt;/p&gt;&lt;p&gt; &lt;a href="https://octodon.social/media/_mCvPclEAQ31dzN-TYI" rel="nofollow noopener" target="_blank"&gt;&lt;span class="invisible"&gt;https://&lt;/span&gt;&lt;span class="ellipsis"&gt;octodon.social/media/_mCvPclEA&lt;/span&gt;&lt;span class="invisible"&gt;Q31dzN-TYI&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;</content>
    <link rel="mentioned" ostatus:object-type="http://activitystrea.ms/schema/1.0/collection" href="http://activityschema.org/collection/public"/>
    <category term="nsfw"/>
    <link rel="enclosure" type="image/png" length="248146" href="https://assets.octodon.social/media_attachments/files/001/246/932/original/a007fb0899bb6024.png"/>
    <mastodon:scope>public</mastodon:scope>
    <link rel="alternate" type="text/html" href="https://octodon.social/@kingu_platypus_gidora/99485066158302598"/>
    <link rel="self" type="application/atom+xml" href="https://octodon.social/users/kingu_platypus_gidora/updates/341245.atom"/>
    <ostatus:conversation ref="tag:octodon.social,2018-02-07:objectId=5032987:objectType=Conversation"/>
  </entry>
</feed>
````

The interesting bit is the `<category term="nsfw"/>` in the item entry.

**Comment by tobiasd** [comment]
If that category is set, we could just add a tag to the posting so the addon can collapse the posting if the user is using that addon.

**Comment by hoergen** [comment]
We should fix this in the upcoming release with Mastodon AP, because people keep sharing such photos from example this account https://glitterkitten.co.uk/@sophia in my timeline.

**Comment by schmaker** [comment]
Just want to bump this as it's still an issue 5 years later. 2023.05

https://mastodonczech.cz/@HPrahy/111211809526026904 (safe)
https://schmaker.eu/display/2cc3d87f-ffce678fe7462cdf-2d0bb054 (not safe)

**Comment by hoergen** [comment]
Support bump

**Comment by schmaker** [comment]
Guess PR https://github.com/friendica/friendica/pull/13876 fixes it?

**Comment by MrPetovan** [comment]
Yes, since #13845 is a duplicate of this, good point.
