### ISSUE TITLE
Attempting fresh install of 3.6 gives blank page

### ISSUE THREAD

**Issue by smth** [friendica/friendica#4672]
I did the following:

1. Downloaded the 3.6 release zip
2. Added the addons
3. Browsed to root (in my local dev environment)
4. Found a blank page (no errors)

If I follow the same steps using 3.5.4 I get the System check (albeit with bug https://github.com/friendica/friendica/issues/3828)

**Comment by annando** [comment]
Have you activated a PHP logfile? There we should see the PHP error.

**Comment by smth** [comment]
Yes, but no errors are generated.

**Comment by annando** [comment]
Which ZIP-file have you used? From this version on we are using the composer for all of our external libraries. I'm currently unsure if possibly you got a file without these.

**Comment by smth** [comment]
friendica-full-3.6.zip, from the releases page. There is at least some composer stuff present, so was assuming it's all there..

![vendor](https://user-images.githubusercontent.com/1375708/37866752-d7995648-2f86-11e8-80ea-5013d10a1618.png)

**Comment by annando** [comment]
Which PHP version are you using?

**Comment by smth** [comment]
5.6.30

**Comment by annando** [comment]
I would like to delegate this to @tobiasd - since he created that file.

**Comment by tobiasd** [comment]
Which zip file exactly did you load? You need the [friendica-full-3.6.zip](https://github.com/friendica/friendica/releases/download/3.6/friendica-full-3.6.zip) file, that contains the dependencies.

The other one is the automatically generated archive (I did not find the point to prevent this) that does not include the dependencies. You can execute

    php util/composer.phar install

from your base directory of the Friendica installation, that should fetch the dependencies as well.

**Comment by tobiasd** [comment]
Ok, just saw your reply that you used the correct file :-/ I tested that zip archive in a virtual machine with the Vagrant file and it worked there.

**Comment by tobiasd** [comment]
What OS are you using on the server? I can try to have a look at it in a virtual machine. But cannot really give a timeframe when I'll be able to do so.

Does the server error log contain any hint?

**Comment by smth** [comment]
OSX (I think my setup is as described [here](https://login.bufvc.ac.uk/wayfless.php?entityID=https%3A%2F%2Fidp.ed.ac.uk/shibboleth&target=https%3A%2F%2Flearningonscreen.ac.uk%2Fondemand%2F)).

There were no errors added to the log.

**Comment by tobiasd** [comment]
Ok, OSX is something I cannot test ;-) I see an Apache2 server. What PHP and MySQL versions do you have on OSX?

**Comment by smth** [comment]
Yeah, Apache 2.4.28
PHP 5.6.30
MySQL 5.7.11

**Comment by tobiasd** [comment]
Do you have the php-xml or php-dom package installed?

**Comment by smth** [comment]
I'm guessing that's

![xml](https://user-images.githubusercontent.com/1375708/37867820-be7e3f5c-2f95-11e8-92f1-486333d3e35f.png)

and

![dom](https://user-images.githubusercontent.com/1375708/37867824-c3461226-2f95-11e8-95dd-f1c80b1b0628.png)

**Comment by tobiasd** [comment]
Mmh, that was the PHP package that if missing prevents the installation wizard from starting, that I know of.

**Comment by MrPetovan** [comment]
It's the PHP 5.6 dependency issue all over again. It's been fixed on `develop` but not on `master`.

**Comment by MrPetovan** [comment]
Fixed by #4662, please look over there for the manual fix until we release a new stable version.

**Comment by smth** [comment]
@MrPetovan as suggested in #4662, I ran `util/composer.phar update paragonie/constant_time_encoding` (composer is in util in 3.6 / master branch). It didn't seem to help. Here is what was returned:

```
Package "paragonie/constant_time_encoding" listed for update is not installed. Ignoring.
Loading composer repositories with package information
Updating dependencies (including require-dev)          
Reading bower.json of bower-asset/base64 (1.0.1)
Could not fetch https://api.github.com/repos/davidchambers/Base64.js/commits/b2d49f347ed1bce61000a82769bffc837b7c79dc, please create a GitHub OAuth token to go over the API rate limit
```
...I created a token...
```
Token stored successfully.
Nothing to install or update                                
Generating optimized autoload files
```

**Comment by smth** [comment]
"Nothing to install" with my lock file.

Replaced it with the one above and got:
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Package operations: 12 installs, 0 updates, 0 removals
  - Installing asika/simple-console (1.0.3): Downloading (100%)         
  - Installing rapidwebltd/rw-file-cache (v1.2.5): Downloading (100%)         
  - Installing psr/cache (1.0.1): Downloading (100%)         
  - Installing rapidwebltd/rw-file-cache-psr-6 (v1.0.0): Downloading (100%)       - Installing paragonie/sodium_compat (v1.6.0): Downloading (100%)         
  - Installing paragonie/constant_time_encoding (v1.0.2): Downloading (100%)      - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Downloading (100%)         
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.0): Downloading (100%)         
  - Installing paragonie/certainty (v1.0.2): Downloading (100%)         
  - Installing divineomega/password_exposed (v2.4.0): Downloading (100%)        paragonie/sodium_compat suggests installing ext-libsodium (PHP < 7.0: Better performance, password hashing (Argon2i), secure memory management (memzero), and better security.)
paragonie/sodium_compat suggests installing ext-sodium (PHP >= 7.0: Better performance, password hashing (Argon2i), secure memory management (memzero), and better security.)
guzzlehttp/guzzle suggests installing psr/log (Required for using the Log middleware)
Generating optimized autoload files
```
Still blank screen. Then ran `php util/composer.phar update paragonie/constant_time_encoding`:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)          
Package operations: 0 installs, 1 update, 0 removals        
  - Updating paragonie/constant_time_encoding (v1.0.2 => v1.0.4): Downloading (100%)         
Writing lock file
Generating optimized autoload files
```
Still seeing the blank screen.

**Comment by MrPetovan** [comment]
Ok, we're progressing. Still no error in the PHP log?

Can you temporarily add 
```php
ini_set('display_errors', true);
```

At the top of your `index.php` file?

**Comment by smth** [comment]
Still no errors in the log. `ini_set('display_errors', true);` made no difference.

The last errors I got were after cloning from master, and before running `util/composer.phar install` for the first time. These errors appeared in the log and on screen.

**Comment by MrPetovan** [comment]
Damn, I'm stumped, I'm not sure what more to suggest without any explicit error message.

**Comment by MrPetovan** [comment]
PHP 7.0 is always recommended, at least for performance reasons. If the `develop` branch doesn't work either, then I'm guessing something else is wrong.

**Comment by smth** [comment]
Yup, there's something else wrong. Same problem with PHP 7.1.13.
