### ISSUE TITLE
Adding Code-Coverage to the Friendica code-base

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#5568]
It's not **that** important, but maybe we can enable the Code-Coverage for Friendica.
We are currently good at track to add tests so we should have an overview about the test coverage :-)
=> https://phpunit.de/manual/5.7/en/code-coverage-analysis.html
=> what about using https://codecov.io for graphical summaries? (f.e. https://codecov.io/gh/nextcloud/server )

@rudloff I'm calling you as the test-expert :-)

**Comment by nupplaphil** [comment]
@Rudloff do you know how we can set the develop branch as the default branch for codecov.io ? Currently, it would take "master" i guess

**Comment by Rudloff** [comment]
It is explained here: https://docs.codecov.io/docs/codecov-yaml#section-master-copy

**Comment by nupplaphil** [comment]
Hm.. As far as I can see, the config doesn't work,  does it? :-/

I checked it with https://codecov.io/validate so the syntax should be OK .

**Comment by Rudloff** [comment]
I think it only looks for the config on the defaultbranche but I'm not sure.

**Comment by nupplaphil** [comment]
The comments are gone, so one thing of the config worked. Sadly I don't know how to locally test the config before creating a PR :-/ 

I'll search for answers ;-)

**Comment by nupplaphil** [comment]
I don't find anything helpful :(
@Rudloff the `develop` branch **is** the default branch, isn't it?

Any ideas? :-(

**Comment by Rudloff** [comment]
Maybe the `.codecov.yml` needs to reach master first? (Like it will only follow a `branch:` instruction it finds in the previous default branch?)

**Comment by nupplaphil** [comment]
So we will wait until 2018.08 will get merged to the master. Hopefully it will work ..

Or is it possible to cherry pick this file to the master? @mrpetovan @tobiasd

**Comment by MrPetovan** [comment]
The release is close-by and it isn't a critical fix so I'm for waiting until it gets merged.

**Comment by nupplaphil** [comment]
funny thing, it now shows the dashboard correctly:
https://codecov.io/gh/friendica/friendica

But the status doesn't work.

Maybe these line
https://github.com/friendica/friendica/blob/31d47ade784c080e15626305e7cc49be85ee67b6/.codecov.yml#L9
should be ```default: false``` ?

**Comment by Rudloff** [comment]
> should be default: false ?

According to the validation tool, `off` is correctly interpreted as `false`:
```json
      "patch": {
        "default": false, 
        "source": {
          "flags": [
            "source"
          ], 
          "target": 80.0
        }, 
        "backend": {
          "flags": [
            "backend"
          ], 
          "target": 80.0
        }
      }
```

**Comment by nupplaphil** [comment]
Some news after my conversation with the codecov support:

**Comment in PR**
The comment in #5685 seems to be a temporary problem during a migration of codecov. They had some strange issues during it. So our config `comment: off` is valid and should work.

**Differences between changes in github and codecov**
Sometimes, there are different "changes" in codecov rather than the "Diff" tab shows (f.e. https://codecov.io/gh/friendica/friendica/pull/5728/changes ). This is described in https://docs.codecov.io/docs/unexpected-coverage-changes that it depends on some factors during the testing. So for them, it's "works as designed"

**YML-File**
Our yml-file **is** valid. It is shown f.e. here https://codecov.io/gh/friendica/friendica/commit/a3570d00273b974270620ccbd5e080d628f422ec/build and the support doesn't see any errors so far.

**PR status**
This is the last and currently open issue (I'm afraid that's because I wasn't clear enough with this issue at first). I don't know the rootcause yet, but maybe/hopefully they reply in the next few days (they usually respond in 2-3 days :-) ).

**Comment by nupplaphil** [comment]
Let's have a look if they can help with the last issue ("PR status") and afterwards I'll close this issue :-).

Hopefully they reply until Friday, so I can close it at weekend. But at least on Monday/Tuesday, I think.

**Comment by MrPetovan** [comment]
I've pushed the milestone for this not to block the release, but it will be shipped in this version, not that it matters for users.

**Comment by nupplaphil** [comment]
Unfortunately they replied some days ago that it should work now (which it isn't :-( ) and I'm currently on holidays. So I'll reply them when I'm back.

**Comment by nupplaphil** [comment]
Still doesn't fully work as expected since it should add a check like the travis check.. Maybe until 2019.12 ..

**Comment by nupplaphil** [comment]
I'm closing this issue now since we'll use drone & codecov and there are just minor problems with github (1 of 20 PRs include a strange comment...)
