### ISSUE TITLE
Some forums not visible any more in widget

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#6282]
### Expected behavior
I lost some forums in my forum widget for quite a while now and I "won" an empty forum that is just a normal contact of mine.

### Actual behavior
So at the moment I'm missing

1. Friendica Support
2. Friendica Developers
3. ~~Friendica News~~

And there is a new "forum" called "frank", that is empty. It was a post from that contact, that created this forum entry in the widget. Pls don't ask me how ;)

### Steps to reproduce the problem
The fact I can't reproduce it, I just want to get rid of the forum "frank" and want the other forums back;)

### Friendica version you encountered the problem
2018.12-rc, mariadb, php7

**Comment by MrPetovan** [comment]
Confirmed, I don't have Friendica News anymore either.

**Comment by AlfredSK** [comment]
Friendica News isn't a forum. It's a 'news page' account.

**Comment by hoergen** [comment]
Yes sorry Friendica news was my mistake. Because the address is "news@forum.friendi.ca"

**Comment by hoergen** [comment]
1. Friendica Support appeart again in the forum widget (after 2 weeks)
2. Frank is still there and
3. Friendica Developers is still missing

**Comment by tobiasd** [comment]
Maybe "Frank" is in, because they set the account type to public forum instead of normal user account? So a (mis)configuration on their side?

**Comment by hoergen** [comment]
The contact Frank wasn't a forum as far as I could see it (checked the profile page). Then I deleted the contact and after a day or two "frank" disapeared from the widget.

But still missing the entry "Friendica Developer" even though I get the forum messages in my stream.

**Comment by annando** [comment]
I had a look at it and saw that we need to synchronize this flag to make this work more reliable. I'm still sick at home but finally without fever problems, so I guess I will fix it today.

**Comment by MrPetovan** [comment]
Damn squirrels.

**Comment by annando** [comment]
Should be working now.

**Comment by hoergen** [comment]
Hmm but still not see "Friendica Developer" should I do something? Like unfollow and refollow again?

**Comment by annando** [comment]
No. It should work after the first message that you received over this forum - or after at latest one month.

**Comment by tobiasd** [comment]
@hoergen is it working four you now or did @MrPetovan close this too soon?

**Comment by hoergen** [comment]
I still can't see the Friendica Developer forum. So it hasn't changed yet.

**Comment by tobiasd** [comment]
As the test in the developmers forum went negative, I'm opening this issue again.

**Comment by AlfredSK** [comment]
@hoergen How many forums do you follow? Just a dumb guess but maybe the issue is this...

From src/Content/ForumManager.php:
`$visible_forums = 10;`

**Comment by AlfredSK** [comment]
Hmm. But the list is sorted as well:

````
//sort by last updated item
		$lastitem = true;
````

**Comment by hoergen** [comment]
I follow 18 forums but I can open the collapsed list. Friendica Developer is still not here.. Thanks  @tobiasd for reopening the issue👍

**Comment by annando** [comment]
Go to ```/probe/``` and enter the forum address. It should look this way:
```
Array
(
    [name] => Friendica Developers
    [nick] => developers
    [guid] => 39bbe52a1759d7b4c5e5255395873937
    [url] => https://forum.friendi.ca/profile/developers
    [addr] => developers@forum.friendi.ca
    [alias] => https://forum.friendi.ca/~developers
    [photo] => https://forum.friendi.ca/photo/12535236855c3a4bbc54951497480914-4.jpg?ts=1547324358
    [community] => 1
    [keywords] => friendica developers development coding git
    [location] => 
...
```
How does it look on your system?

**Comment by hoergen** [comment]
It gives me this output

`Array
(
    [name] => Friendica Developers
    [nick] => developers
    [guid] => 39bbe52a1759d7b4c5e5255395873937
    [url] => https://forum.friendi.ca/profile/developers
    [addr] => developers@forum.friendi.ca
    [alias] => https://forum.friendi.ca/~developers
    [photo] => https://forum.friendi.ca/photo/12535236855c3a4bbc54951497480914-4.jpg?ts=1547324358
    [community] => 1
    [keywords] => friendica developers development coding git
    [location] => 
    [about] => [b]The Friendica Developers Group[/b]

This forum is for Friendica developers to discuss the programming and development of the project. Everyone interested in the development of Friendica is invited to participate.
    [batch] => 
    [notify] => https://forum.friendi.ca/dfrn_notify/developers
    [poll] => https://forum.friendi.ca/dfrn_poll/developers
    [request] => https://forum.friendi.ca/dfrn_request/developers
    [confirm] => https://forum.friendi.ca/dfrn_confirm/developers
    [poco] => https://forum.friendi.ca/poco/developers
    [priority] => 0
    [network] => dfrn
    [pubkey] => -----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAmeqyCATTzQGhvu78fTLT
Fk05liL6KXSN09lOQAksCtMBLTp3U0y8Eoqs1zqnSptfk/yo6j8hskatUfWi23y8
UN4+awiI1SYpY3a9KuNDvlS1APrkgBbiKFs2NdQv4or5dSWPRTtkhxQF/9vNaflw
WF6dlPmqpUrMlMRKGk9hML+0Nto9NbwmiJW79x8UFK06Tcy8zzeR2zCIJnxnZ0mp
k/VKLqxiYOJFSUmVu2amgbHBLtwyFe6pNZtSF8Mt973MChOK1QzYmOOawCuzRbeU
GhUiiXYKFCnpwTwMM8IZZMM4T7vuS0FIVc6yZAmN1BtAdgxJzHx/0vx0HXCbybNF
IkQSGU/cgYdHACOI90bHY2HdBRDcTyAAyhTPosgnpmkfbjjg4XAMtsECfrZjPRA6
gNOtbRuHeY0Fsbvhn5HX82NtkqaQqp2/+xqb630MWqTQHSuEnMjutkXH7bNXsnhO
16WCTYpOlQYMTo334HmgDKtHdiTZKOp4TbtIBtQw+e6vTccTYljIMOLWR8vGDZlJ
Vrkr74mzRAiwYXKlQBuelwqkwbZfqa+yAt9VRtwNh39+zOKZaqRKqh7l52hFMpEW
drfP/34tMhcD3ZXukB33uqgsv4TmIP+KsAtklnwMDoW5tADe52qfY3dkL1E+pWv7
PH/WwkuZGieYN6xde9XM3y8CAwEAAQ==
-----END PUBLIC KEY-----

    [baseurl] => https://forum.friendi.ca
)`

**Comment by annando** [comment]
Does it appear now again?

**Comment by hoergen** [comment]
No, it is still not in the widget. :(

**Comment by hoergen** [comment]
I checked the database and I have 3 entries in the contact table.

1. the old developer forum from uberspace (not updated for a long time)
2. the correct devel forum with dfrn
3. the correct devel forum with apub

on both contact-type = 3
url & nurl looking good
```
last update         | successfull update
2018-12-13 04:01:38 | 2019-01-14 11:51:12
```

**Comment by annando** [comment]
Please execute this query:
```select id, uid, network, blocked, pending, archive, hidden, success_update, failure_update, forum, prv from contact where nurl = 'http://forum.friendi.ca/profile/developers';```

**Comment by hoergen** [comment]
`

id | uid | network | blocked | pending | archive | hidden | success_update | failure_update | forum | prv
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
3363 | 0 | dfrn | 0 | 0 | 0 | 0 | 2019-01-15 00:18:33 | 0001-01-01 00:00:00 | 1 | 0
3362 | 1 | apub | 0 | 0 | 0 | 0 | 2019-01-14 11:51:12 | 0001-01-01 00:00:00 | 1 | 0

`

**Comment by annando** [comment]
Ooookay ... I guess the system really forces the use of ActivityPub 😀 

I'm not totally sure why this switched, but that's the reason for the problem. Can you still write posts to the developer forum? (With ```!developers@forum.friendi.ca```)? If this works, then we will simply change the list conditions here. (And we have tested that forum posts already can be done via AP)

**Comment by hoergen** [comment]
Did a testpost

**Comment by AlfredSK** [comment]
Didn't arrive until now.

**Comment by hoergen** [comment]
hmm there is no message waiting in the worker queue, so it should have been delivered.

**Comment by AlfredSK** [comment]
If I look at your contact in the developers forum's contact list it is shown as 'DFRN', not as ActivityPub.
If I look in the contact table of the forum node I have the following:
'hoergen' with UID=3 (3=developers) and network=dfrn
'hoergen' with UID=0 and network=dfrn
'hoergen' with UID=0 and network=stat

But there is no contact with network=apub for you.

**Comment by hoergen** [comment]
Hmm maybe i remove the contact, wait for a day and reconnect again ...

**Comment by annando** [comment]
My current plan is to look what it takes so that AP is able to work with forum posts as well. This had been a plan for the next version, but obviously it happens that Friendica contacts are changed to AP contacts, so it would be good to handle it.

**Comment by annando** [comment]
This whole AP group stuff is too complicated to address it now. So I worked at the whole contact update, so that wrong detected contacts are fixed.

**Comment by hoergen** [comment]
Should I try to reconnect to the forum now? If not, I will do tomorrow

**Comment by annando** [comment]
No, please don't do anything until the PR had been accepted. I want to see if this will fix it.

**Comment by hoergen** [comment]
ok I'll wait your order ;)

**Comment by hoergen** [comment]
It looks like the PR was merged?

**Comment by MrPetovan** [comment]
It was.

**Comment by annando** [comment]
After most likely 24 hours - or when you manually refresh of the contact - this hopefully should be fixed now.

**Comment by hoergen** [comment]
I reconnected to the forum. Don't see the forum yet in the widget. So I wrote 2 comments on posts. Let's wait till tomorrow.

**Comment by hoergen** [comment]
Ok, I was too quick. Now the forum appeared in my widget again. Thanks so much ❤️️

**Comment by annando** [comment]
What do you mean with "reconnected"? Have you removed the contact? If yes, then we will never know, if my coding could have fixed the problem at all ...

**Comment by hoergen** [comment]
Yes I removed the contact  when I wrote "Hmm maybe i remove the contact, wait for a day and reconnect again ...".

I already did that 2 weeks agao, but it didn't change then. Now it changed, so your coding had an effect on that. Because I was repeating the steps and do have now a diferent result.
