### ISSUE TITLE
Setting permissions on posts needs more secure workflow

### ISSUE THREAD

**Issue by hoergen** [friendica/friendica#7308]
If you start a new post, where you want set the permission e.G. that only one or several persons can see that post, you start with this default selection and your using the search field to find the contacts you want to give permissions,, you end up writing a public post: visible for all of your contacts :(

![00_temp](https://user-images.githubusercontent.com/24474762/59976407-3eb9bf80-95c4-11e9-9b85-8b344270dd44.png)

The workaround to not send to all your contacts, you first click on "visible for everybody" (to clean all other selections) and then you select the persons you want to give the permission.

I know this is a tricky part, but we need to solve that, because new users will have their problems to understand in the beginning and even advanced users (like me) are stumbling across that obstacle, because im not using it very often. There are 2 solutions in my mind, but maybe you have better ones?

**Solution 1** could be to add in the same line with the button "Visible to everybody" another button "Clear all permissions" (both bottons of the same size!)

**Solution 2** could be that as soon you are initially changing the permissions, the default permission gets removed and you get a visual feedback, like a red line that your default permissions are removed now. 

**Another little bug** is, that when you once used the search field on the permission window and you deleted your typed words, you won't get back the initial list of contacts and groups. You have to keep al of them in your mind.

**Comment by MrPetovan** [comment]
The real solution is to ditch this display entirely and use 4 distinct fields with auto completion:
- Allowed contacts
- Disallowed contacts
- Allowed groups
- Disallowed groups

Starting typing in any of those fields would bring the autocompletion list of contacts/groups matching the string, and selecting one would add it to the field like a Bootstrap Tag Input: https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/

This way you see exactly where your post will be going at all time without having a massive list of contacts to browse for selected permissions.

**Comment by hoergen** [comment]
Or just two fields "Allowed" and "Disallowed"

**Comment by MrPetovan** [comment]
It's possible too, the "tags" would have to be visibly different to separate their type (single contact or group).

**Comment by MrPetovan** [comment]
Did you give a try to [the new Compose page](https://horche.demkontinuum.de/compose)?

**Comment by hoergen** [comment]
Didn't see yet. Thanks for pointing me to it. Is it a mockup? Would like to see how it is, when you added contacts in restricted posts and how you edit them (remove)

Is it possible to color the active part green and the non active part red? 

![00_temp](https://user-images.githubusercontent.com/24474762/63226903-98172700-c1e0-11e9-85d3-1bade69f7f94.jpg)

**Comment by hoergen** [comment]
The colors should have more signal function like

![00_temp](https://user-images.githubusercontent.com/24474762/63226972-9dc13c80-c1e1-11e9-9279-4d42b78179ef.jpg)

**Comment by MrPetovan** [comment]
It isn't a mockup, it is fully functional but since it replaces the post modal in a couple of places, it's been "hidden" behind an "Additional Feature" switch in your settings.

Active and inactive don't use such strong colors. The usual is more like:
- Active: colored.
- Inactive: greyed/faded out.

**Comment by AlfredSK** [comment]
Please don't use such signal/alert colors. I'd like to keep my eyesight. :-) Thank you!

**Comment by hoergen** [comment]
Hmm ok, then i need to clear the cache because the search for users or group isn't working here.

**Comment by hoergen** [comment]
Hmm can't find the switch
![00_temp](https://user-images.githubusercontent.com/24474762/63227576-1d520a00-c1e8-11e9-83be-27f2eaf80b5d.jpg)

**Comment by MrPetovan** [comment]
In General.

**Comment by hoergen** [comment]
Still a cache problem? Or am I blind?
![00_temp](https://user-images.githubusercontent.com/24474762/63227655-095ad800-c1e9-11e9-8530-7e7ec3e76bf2.jpg)

**Comment by AlfredSK** [comment]
It's not an additional feature. You find the option in settings -> display -> custom theme settings.

**Comment by hoergen** [comment]
Ahhhhh there it is
![00_temp](https://user-images.githubusercontent.com/24474762/63227820-03fe8d00-c1eb-11e9-865f-bc471613fe39.jpg)

**Comment by hoergen** [comment]
The contact search (ajax) is not working and the option to send the message via addons e.g. Twitter, Tumblr is not there.

**Comment by AlfredSK** [comment]
You have to refresh -
your browser's cache!
Yo!
(works here)

**Comment by MrPetovan** [comment]
Any error in the Web Developer Console?

**Comment by hoergen** [comment]
```
SyntaxError: invalid regexp group linkPreview.js:1:1
TypeError: $textarea.linkPreview is not a function post:530:13
    <anonymous> https://horche.demkontinuum.de/compose/post:530
    jQuery 4
        i
        fireWith
        ready
        J

```

**Comment by MrPetovan** [comment]
Nine years ago the Javascript support for negative lookbehind (syntax is `(?<!...)`) was spotty at best but it should be almost universal now, not much I can do about it.

**Comment by annando** [comment]
@MrPetovan would you consider this issue solved with the new dialogue?

**Comment by hoergen** [comment]
I wouldn't say, that it is completely solved, because in the default composer page the issue is still there.
The new composer page is far a better approach to the problem, but it is not integrated into the usage of the theme. It makes it more clumsey because, if you start a new post, a new page is loaded, instead e.g. in vier, where you have on the top of the time line the possibility to write your post without leaving the actual page.

So in terms of the problem, this solution is better, but in terms of usablitiy it is worse, not default and not integrated well.

Therefore no.

**Comment by MrPetovan** [comment]
What is the difference between opening a modal and loading a different page, given that both forms will reload the `/network` page?

Is it just about replacing the current ACL selector in the permissions tab with the new one I created for the `/compose` page?

**Comment by hoergen** [comment]
The difference between opening a modal and loading a different page is: Open a modal or loading a different page ;) 

As a technical solution it is maybe kind of similar. But as I explained above in terms of **usability** it is something completely different. the it may applications like e.g. modern email programs, where you don't have to switch the actual view (go to the email writing page) to be able to write a new email, or to answer an email. You get a "modal" window here you write your email, that disappears again, when you send or close it. 
And there maybe the situation where you think "hmm i might write a post" then you click on the compose page, but then you discard your thoughts and you go back on "somewhere on your timeline". For standard users completely unacceptable, for more technical users annoying, because you have to search the post that you last read to be able to read further.

And there is another big problem: Scalability . On small instances this maybe a nice workaround to load a new page for writing a new post and loading again the timeline, when you sent it. But if you are short on resources or you have a node with lots of users, you automatically increase the load of your system with this solution.

Don't get me wrong. I like the new composer option. But a new page is not an "integration". It's the opposite.  

That's why I suggested if there is maybe the possibility to integrate it like theme vier it does (top of the page) or to make it modal as well?

**Comment by MrPetovan** [comment]
I hear you, but then it seems that it matches the wish expressed in this issue: #4599

If it is the last remaining need with the current modal, please close this issue and bump the other by adding a comment expressing your support.

The new page absolutely can't be in a modal because it uses the modal itself (to attach images).

Like I said, the best I can do is replace the current permission tab with the new ACL fields, would it be enough to consider this issue resolved?

**Comment by hoergen** [comment]
Ok, then let it put me like that: My issue was about the modal. You created a really nice but other possibility on a different page . But the problem is still not solved, because it still exists in the modal.

**Comment by MrPetovan** [comment]
Fair enough, that's what I wanted to hear since this issue went multiple ways.

**Comment by hoergen** [comment]
And why you didn't say that in the beginning?

**Comment by MrPetovan** [comment]
Because this issue went multiple ways, so I combed through the multiple ways it went until finding the crux of the issue.

**Comment by MrPetovan** [comment]
I won't be able to complete this issue this milestone, the ACL part of the compose page needs special attention to be backported to the modal just for frio (because of the Bootstrap dependency).

**Comment by MrPetovan** [comment]
This is taking way more time than expected. I had made a questionable design decision when creating the Compose page and no I'm having to redo it to make it compatible with vier.

**Comment by hoergen** [comment]
I know it is not an easy part and it is even more difficult to implement the design to the already existing default compose dialog. 👍

**Comment by MrPetovan** [comment]
I'm now at 90% of the way. There's a weird lingering error where selecting "Limited visibility" without touching the permission fields defaults submitted permissions to "private-self" which isn't  what shows (followers).

**Comment by annando** [comment]
BTW: For the composer page it would be good if you could respect the setting in the mail settings if the user wants to send public messages to the mail contacts or not.

**Comment by MrPetovan** [comment]
I don't think it is related to the compose page. This seems to be a `mod/item` feature where if the provided ACL is "public", then the mail setting should be checked for mail contact delivery. What would be the visual/practical difference in the ACL whether this option is enabled or disabled?

**Comment by annando** [comment]
for the new composer page you created a new "virtual" group with all contacts of a user. This also contains the mail users as I experienced, when I tried it out. I think this option should control if the mail users are included or not.

**Comment by MrPetovan** [comment]
Ok, so it should be enacted at the Group level.

**Comment by MrPetovan** [comment]
@hoergen Please test the new ACL if it is to your taste.

**Comment by annando** [comment]
@MrPetovan what do you do, if not? :-)

**Comment by MrPetovan** [comment]
I expect constructive criticism and actionable complaints I can use to improve the system for everyone.

**Comment by hoergen** [comment]
Hehe, it's not about my taste. My opinion is, that everything we change at the front end should not disturb the workflow or make it more complicated or different as it is already. I know that it is a very difficult task, because we always have to think about the most lo-tech experienced user aka it should be as intuitive as possible.

My "opinions"

1. I like the way how you add contacts to the "deliver" field, but if the name has a "space" the search stops (breaks?)
2. the compose dialog should be a popup like the standard one
3. not sure, but maybe there should be a button to set the default location text again, if you played with it and deleted the default insert.

**Comment by MrPetovan** [comment]
1. Good point, the tags input is configured to add a new tag on pressing space, I can remove this trigger.
2. You can disable the compose page in the Theme Customization settings and use the modal again, it now uses the same ACL as the compose page.
3. Not sure about that, the default location string can still be manually readded, at this point in the use case there's no need for a default because of the changes that already happened.
