### ISSUE TITLE
I can't post to my own forum

### ISSUE THREAD

**Issue by anubis2814** [friendica/friendica#7803]
Hey everyone. I Have just created an open forum (steampunk@nerdica.net) and no matter what I do I can't post on the forum with my personal account. My normal profile can't post to it at all. Please help.  At first it was letting me post with !steampunk@nerdica.net but not without it, and I was very confused as to why some forums neeed it and some don't.  Now it won't let me post anything or even email the forum as it just vanishes into the aether never to be seen again.  I log into the forum and I have no email.  Any idea whats happening? Also the unfollow button seems to not work on the forum as I followed and then unfollowed steampunk after making myself a delegate on steampunk then tried to refollow steampunk and there was no option other than the unfollow button.  Any time I clicked it, it said that unfollow is not working at this time.

**Comment by hoergen** [comment]
I have difficulties to understand some points

1. What is the difference between your "personal" and your "normal" account?
2. You _always_ post in a forum with the ! bang notation 
3. Maybe you didn't see the ! bang notation in other posts because some people put it in the last line, instead of first.
4. What do you mean with " I log into the forum and I have no email." ?
5. Is your private/personal account member/contact of that forum?
6. Please make some screenshots what do you exactly mean. Im not really sure if I understand your problem?

**Comment by anubis2814** [comment]
!, no difference
2 I have not needed to in several other forums, I'm wondering what the difference is
3. No I have posted on several other forums without the bang.
![Untitled](https://user-images.githubusercontent.com/57196483/68077678-5b4ddb80-fd9e-11e9-8129-6ef149c84ec5.png)
4.  I send the forum an email from my personal account.  I then log into the forum and there should be email waiting in the inbox but there is nothing.
5. yes
6.  I seem to have been able to post from my page with the bang while logged into my personal account but I can't post while viewing the steampunk page.  

The unfollow button glitch seems to have fixed itself now

**Comment by hoergen** [comment]
1. Perfect 👍 ✅
2. + 3. We talked about that here at the hackathon. There was a bug were you didn't need it, but it should be fixed already and  you should always use it ;)
4. Hmm that should work, as you said, that you are in contact with the forum. I tested it and it worked here.
5. 👍 ✅
6. Maybe try:  login with your forum acount, go to the contact page, delete your private account, switch to your private account and connect again to the forum. And give it some minutes. And then try topic 4 again.

**Comment by anubis2814** [comment]
The email system just fixed itself.  I'm still having problems posting to the group even with the !. That said things have been fixing themselves making me wonder if there isn't something going on in the background in terms of repairs.
