### ISSUE TITLE
Wrong notification URL

### ISSUE THREAD

**Issue by nupplaphil** [friendica/friendica#8187]
I would love it because now i have some ugly side effects, so that i cant react on contact requests. It throws an error like this

```
#0 [internal function]: Friendica\Module\HTTPException\PageNotFound::content(Array)
#1 /Friendica_Install/htdocs/src/App/Page.php(310): call_user_func(Array, Array)
#2 /Friendica_Install/htdocs/src/App/Page.php(364): Friendica\App\Page->initContent(Object(Friendica\App\Module), Object(Friendica\App\Mode))
#3 /Friendica_Install/htdocs/src/App.php(583): Friendica\App\Page->run(Object(Friendica\App), Object(Friendica\App\BaseURL), Object(Friendica\App\Mode), Object(Friendica\App\Module), Object(Friendica\Core\L10n), Object(Friendica\Core\Config\JitConfig), Object(Friendica\Core\PConfig\JitPConfig))
#4 /Friendica_Install/htdocs/index.php(27): Friendica\App->runFrontend(Object(Friendica\App\Module), Object(Friendica\App\Router), Object(Friendica\Core\PConfig\JitPConfig), Object(Friendica\App\Authentication), Object(Friendica\App\Page))
#5 {main}
```

_Originally posted by @hoergen in https://github.com/friendica/friendica/issues/8181#issuecomment-578983328_

**Comment by nupplaphil** [comment]
`https://horche.demkontinuum.de/notifications/-1`

_Originally posted by @hoergen in https://github.com/friendica/friendica/issues/8181#issuecomment-579001046_

**Comment by nupplaphil** [comment]
@hoergen where did you click to get these ugly notification URL? in a dropdownfield or in the notification section at a tab?

**Comment by hoergen** [comment]
1. I clicked the notification section. 
2. Then it opened   `https://horche.demkontinuum.de/notifications/intros/924` 
3. Then  I clicked the trashcan "Verwerfen"
4. Then I got the errorpage with the message

**Comment by nupplaphil** [comment]
thx

**Comment by hoergen** [comment]
I pulled some minutes ago and wanted to accept a contact as follower then i got an empty Browser page with this message

```
Nicht gefunden

Friendica\Repository\Introduction record not found.

#0 /var/customers/webs/hoergenWeb/horche.demkontinuum.de/htdocs/src/Repository/Introduction.php(33): Friendica\BaseRepository->selectFirst(Array)
#1 /var/customers/webs/hoergenWeb/horche.demkontinuum.de/htdocs/src/Module/FollowConfirm.php(24): Friendica\Repository\Introduction->selectFirst(Array)
#2 [internal function]: Friendica\Module\FollowConfirm::post(Array)
#3 /var/customers/webs/hoergenWeb/horche.demkontinuum.de/htdocs/src/App/Module.php(256): call_user_func(Array, Array)
#4 /var/customers/webs/hoergenWeb/horche.demkontinuum.de/htdocs/src/App.php(578): Friendica\App\Module->run(Object(Friendica\Core\L10n), Object(Friendica\App\BaseURL), Object(Friendica\Util\Logger\StreamLogger), Array, Array)
#5 /var/customers/webs/hoergenWeb/horche.demkontinuum.de/htdocs/index.php(27): Friendica\App->runFrontend(Object(Friendica\App\Module), Object(Friendica\App\Router), Object(Friendica\Core\PConfig\JitPConfig), Object(Friendica\App\Authentication), Object(Friendica\App\Page))
#6 {main}
```

![00_temp](https://user-images.githubusercontent.com/24474762/73302277-a7c97b80-4214-11ea-9845-281f849222fe.png)

**Comment by MrPetovan** [comment]
What is the URL in the address bar?

**Comment by AlfredSK** [comment]
A user of my node reported the same thing...
https://forum.friendi.ca/display/0b6b25a8-125e-3085-f1a7-884023383548

The URL was https://friendica.server/follow_confirm

**Comment by MrPetovan** [comment]
Thanks!

**Comment by nupplaphil** [comment]
>     1. I clicked the notification section.
> 
>     2. Then it opened   `https://horche.demkontinuum.de/notifications/intros/924`
> 
>     3. Then  I clicked the trashcan "Verwerfen"
> 
>     4. Then I got the errorpage with the message

Fixed with https://github.com/friendica/friendica/pull/8186

**Comment by hoergen** [comment]
It is still not fixed. I get still the "Page not found" error message after pulling (some minutes ago)

**Comment by nupplaphil** [comment]
yes .. I thought #8194 will get merged before you notice it ;-)

**Comment by hoergen** [comment]
Hehehe sorry ;)
