### ISSUE TITLE
gnusocial export stopped working

### ISSUE THREAD

**Issue by adrelanos** [friendica/friendica#8603]
### Expected behavior

post export to gnusocial

### Actual behavior

post not exported to gnusocial

### Steps to reproduce the problem

set up gnu social export

> Currently connected to: whonix

check `Allow posting to GNU Social`
check `Send public postings to GNU Social by default`

save settings

has worked before.

https://meld.de/display/a8e4f565-145e-af1b-bac2-7a3576178511
->
https://gnusocial.cc/notice/1228585
OK

but https://meld.de/display/a8e4f565-175e-b369-c9ac-f64047269530 or https://meld.de/display/a8e4f565-125e-b42a-e775-2a9559842554 was not forwarded to gnusocial.

Didn't touch any gnusocial settings in meanwhile since I was happy that it was functional.

### Friendica version you encountered the problem

https://meld.de/profile/whonix

//cc @copiis

**Comment by copiis** [comment]
Whe Had some Problem with the worker last days, should work now.

**Comment by adrelanos** [comment]
Tried after your comment.

Not fixed unfortunately. https://meld.de/display/a8e4f565-325e-b6f5-8218-7c1571067742 wasn't forwarded to either gnusocial or diaspora (#8604).

**Comment by dmpink** [comment]
Option Allow posting to GNU Social is became unchecked after click on Save button. Export not working.
![image](https://user-images.githubusercontent.com/23205416/157339438-347bdfb9-5ee0-4fa2-8a50-b4de137821ae.png)

**Comment by annando** [comment]
@dmpink For a long time I thought about completely removing this addon because i don't see a reason for it anymore. For which purpose do you want to use it?

**Comment by dmpink** [comment]
@annando The main idea is to post from 2 (maybe more) different friendica's profiles to one gnusocial profile.
