### ISSUE TITLE
Posts to public forums send ActivityPub objects that can't be dereferenced

### ISSUE THREAD

**Issue by vpzomtrrfrt** [friendica/friendica#8860]
### Expected behavior
All public objects should be retrievable at their ActivityPub IDs
### Actual behavior
Posting to a Public Forum sends an Announce to its followers, but attempting to fetch the referenced `object` results in a 404. It seems this was referenced in #6100, but perhaps not related to the resulting fix?
### Steps to reproduce the problem
- Create a Public Forum account
- Follow it from an ActivityPub server
- Post to the forum from Friendica
### Friendica version you encountered the problem
42a3f278

### Friendica source (git, zip)
git

### PHP version
7.4.7

### SQL version
10.1.30-MariaDB

**Comment by MrPetovan** [comment]
Because of the transfer of post ownership, forum posts are tricky. They are copied on the forum node, but weren't originally posted on the forum node, which may produce this discrepancy.

@annando ?

**Comment by annando** [comment]
@vpzomtrrfrt can you post an example here? Maybe this explains why forum posts doesn't seem to work with Pleroma.

**Comment by annando** [comment]
I just did some tests. I experienced some really odd behaviour. I will have a look at it tomorrow. We shouldn't do the release when this hadn't been fixed.

**Comment by annando** [comment]
The odd behaviour is fixed. I'm not sure if this fixes this issue, but the blocking bug had been fixed.

**Comment by vpzomtrrfrt** [comment]
Seems to still not be working, even with the code from #8862

**Comment by annando** [comment]
@vpzomtrrfrt can you post some example? I guess I need to have some test material.

**Comment by vpzomtrrfrt** [comment]
I'm not really sure how to do that, what do you want me to post?

**Comment by annando** [comment]
I would like to have this "announce" message and the id that can't be fetched.

**Comment by vpzomtrrfrt** [comment]
This is the object received by Pleroma:

```json
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://w3id.org/security/v1",
    {
      "vcard": "http://www.w3.org/2006/vcard/ns#",
      "dfrn": "http://purl.org/macgirvin/dfrn/1.0/",
      "diaspora": "https://diasporafoundation.org/ns/",
      "litepub": "http://litepub.social/ns#",
      "manuallyApprovesFollowers": "as:manuallyApprovesFollowers",
      "sensitive": "as:sensitive",
      "Hashtag": "as:Hashtag",
      "directMessage": "litepub:directMessage"
    }
  ],
  "id": "http://testfr.localhost/objects/c55e3211-595f-0a06-a360-fa5784129901/Announce",
  "type": "Announce",
  "actor": "http://testfr.localhost/profile/somegroup",
  "published": "2020-07-11T18:36:19Z",
  "instrument": {
    "type": "Service",
    "name": "Friendica 'Red Hot Poker' 2020.06-rc-1355",
    "url": "http://testfr.localhost"
  },
  "to": [
    "https://www.w3.org/ns/activitystreams#Public",
    "http://testfr.localhost/profile/somegroup"
  ],
  "cc": [
    "http://testfr.localhost/followers/somegroup"
  ],
  "object": "http://testfr.localhost/objects/c55e3211-595f-0a06-a360-fa5784129901",
  "signature": {
    "type": "RsaSignature2017",
    "nonce": "b1b44c3287456e96f020d3821e2c23bcd9950993868df3abcbb2c3bb2e502926",
    "creator": "http://testfr.localhost/profile/somegroup#main-key",
    "created": "2020-07-11T18:36:20Z",
    "signatureValue": "zri2148dtUUCdgV0YApV4u51EyxLbR0RBOwaMY0knavXUy+QM8qOYeuc92LHLdpPlgYtbWHr0YxZdWSdnT+kUuvFdAHNgOEfMAx8eE/hv6CK/wvbvwTfQcRlXT/KtKu3id6rvFPn7j/TBD2kdP8y15lPRljd/tlv21cpLL6I4mUjde/DvohgE2vHrrc7iDwTrEe0Df6lDxzg5+oaFroBjIVlYO4qtCBRlLR7yxazSYdFW1j3Tmvdu622Gn2l+DapHi3v1yhHSe8sRupEIJ4rmcAGgjuZa6hw1ECEWZsjy/GD8Qh/USeouYQ+NfJ6nrPtqyRaybEhygArdMlJpXo1SAmGAnGcXdBIYX+ZetsLLRgP82/IZU5Bpk9HbEMXPj/cdZv1Od1dwqyeWmEYHqahAL1V207fQfYoVglB+JBZPhtcgoPWIVtwafxLs4dk2pq24mfqvNA1LrvCeRkP1apAcisoNxaUVZ1teGqmNdt4ivmvH1cIXMz6vv9xUbFyYRleaIPgTYTItjeXJROE8c5ZLre/pb4j3wqEguRPdVibkDz8IwHy+Uu8uHE+5Wibua+67L73LvEmPJ4d3QhhKQe0ZsboGzHGoSJHokXYYOkGpVLWI/ekmh6XXwGUBrUflTjiR2AgjxBo6ama+9wTZ3858SH6tl0CTbnX45cHkYdKq8s="
  }
}
```

Attempting to fetch "http://testfr.localhost/objects/c55e3211-595f-0a06-a360-fa5784129901" with "Accept: application/activity+json" results in a Not Found page

**Comment by annando** [comment]
Are you testing on your local system with both Friendica and Pleroma on the same system? Also the forum account and the personal account are on the same system?

**Comment by vpzomtrrfrt** [comment]
Yes.

**Comment by vpzomtrrfrt** [comment]
```
diff --git a/src/Protocol/ActivityPub/Transmitter.php b/src/Protocol/ActivityPub/Transmitter.php
index 6bf507ed8..5d33c97fb 100644
--- a/src/Protocol/ActivityPub/Transmitter.php
+++ b/src/Protocol/ActivityPub/Transmitter.php
@@ -857,7 +857,7 @@ class Transmitter
                        return false;
                }

-               if ($item['wall'] && ($item['uri'] == $item['parent-uri'])) {
+               if ($item['wall'] && ($item['uri'] == $item['parent-uri']) && !$object_mode) {
                        $owner = User::getOwnerDataById($item['uid']);
                        if (($owner['account-type'] == User::ACCOUNT_TYPE_COMMUNITY) && ($item['author-link'] != $owner['url'])) {
                                $type = 'Announce';
```

Changing this seems to have fixed it, but I don't really know what it means

**Comment by MrPetovan** [comment]
Thank you for the diff, I defer to @annando to explain the meaning of the change.

**Comment by annando** [comment]
This simply controls how the generated activity object is looking like.

**Comment by annando** [comment]
With PR https://github.com/friendica/friendica/pull/9061 this should now work.

**Comment by vpzomtrrfrt** [comment]
Confirmed, looks like it's resolved now
