### ISSUE TITLE
[phpmailer] Double Message-ID header in some notification mails - RFC violation

### ISSUE THREAD

**Issue by AlfredSK** [friendica/friendica#9142]
### Expected behavior
A mail must contain one Message-ID header. Two Message-ID headers are a RFC violation.
Setting the message ID is a task for the used mailer but not for the application, I think.

### Actual behavior
Some (!) - not all - notification messages have two Message-ID headers. I got bounce mails because of this RFC violation.

I think the problem is here:
https://github.com/friendica/friendica/blob/40a93223ee0fcc77d541f2ef9c3c02a2722a41fe/include/enotify.php#L523

Example:
```
Date: Fri, 4 Sep 2020 00:42:35 +0000
To: libranet@someremotedomain.com
From: "LIBRANET.de" <admin@libranet.de>
Reply-To: "LIBRANET.de" <admin@libranet.de>
Subject: [Friendica:Notify] Example User tagged you (exampleuser@libranet.de)
Message-ID: <Blx5qbY0czTL40q3ZNGWzGjgvszFW9ECBcRJWwGU@librabox2.libranet.de>
X-Mailer: PHPMailer 6.1.4 (https://github.com/PHPMailer/PHPMailer)
Precedence: list
X-Friendica-Host: libranet.de
X-Friendica-Platform: Friendica
X-Friendica-Version: 2020.09-dev
List-ID: <notification.libranet.de>
List-Archive: <https://libranet.de/notifications/system>
X-Friendica-Account: <exampleuser@libranet.de>
Message-ID: <83810059@libranet.de>
MIME-Version: 1.0
Content-Type: multipart/alternative;
....
```

### Steps to reproduce the problem
I do use the phpmailer add-on. That add-on creates a message ID with the local hostname as domain part. That's okay.

But enotify adds another message ID under some circumstances. Most other notification mails have a `References: <83200641@libranet.de>` and `In-Reply-To: <83200641@libranet.de>` instead. That works. But the two message IDs are bad.

### Friendica version you encountered the problem
2020.09-dev

### Friendica source (git, zip)
git

### PHP version
7.4

### SQL version
10.3 MariaDB

**Comment by AlfredSK** [comment]
Maybe we can use a `X-...` header instead.

**Comment by AlfredSK** [comment]
Nope. Now the second message ID looks different. But still, there are two of them.

```
Return-Path: <admin@libranet.de>
X-Original-To: alfred@libranet.de
Delivered-To: alfred@libranet.de
Received: from localhost (localhost.localdomain [127.0.0.1])
	by mx10.libranet.de (Postfix) with ESMTP id C5B0C20F58
	for <alfred@libranet.de>; Sun,  6 Sep 2020 19:23:24 +0000 (UTC)
X-Quarantine-ID: <T2La3ORGyk6f>
X-Amavis-Alert: BAD HEADER SECTION, Duplicate header field: "Message-ID"
Received: from mx10.libranet.de ([127.0.0.1])
	by localhost (j125736.servers.jiffybox.net [127.0.0.1]) (amavisd-new, port 10024)
	with ESMTP id T2La3ORGyk6f for <alfred@libranet.de>;
	Sun,  6 Sep 2020 19:23:23 +0000 (UTC)
Received: from libranet.de (libranet.de [IPv6:2a01:4f9:2b:289e::2])
	(using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
	 key-exchange X25519 server-signature RSA-PSS (2048 bits) server-digest SHA256)
	(No client certificate requested)
	by mx10.libranet.de (Postfix) with ESMTPSA id BCD7F20F33
	for <alfred@libranet.de>; Sun,  6 Sep 2020 19:23:23 +0000 (UTC)
Date: Sun, 6 Sep 2020 19:23:23 +0000
To: alfred@libranet.de
From: "LIBRANET.de" <admin@libranet.de>
Reply-To: "LIBRANET.de" <admin@libranet.de>
Subject: [Friendica:Notify] Comment to conversation #84039392 by hoergen on Friendica (alfred@libranet.de)
Message-ID: <rooCzsPw4y9yXWrKgMx5TgCwVTGlw5okllOphy4UPY0@libranet.de>
X-Mailer: PHPMailer 6.1.4 (https://github.com/PHPMailer/PHPMailer)
Precedence: list
X-Friendica-Host: libranet.de
X-Friendica-Platform: Friendica
X-Friendica-Version: 2020.09-rc
List-ID: <notification.libranet.de>
List-Archive: <https://libranet.de/notifications/system>
X-Friendica-Account: <alfred@libranet.de>
Message-ID: <962c3e10-165f-5383-5159-72a144813680@librabox2.libranet.de>
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="b1_rooCzsPw4y9yXWrKgMx5TgCwVTGlw5okllOphy4UPY0"
```

**Comment by annando** [comment]
Hmm ... I guess that the second ("our") message id is added **after** the first had been added. Possibly I have to have a look at the addon itself.

**Comment by AlfredSK** [comment]
There are notification mails w/o the second message ID (the one at the end). These mails look completely right. 
I think there must be some condition that checks for the header and then triggers the 'add additional id header' in entity.php.
But that's just a guess from my observations of the mails I get. 👍

**Comment by annando** [comment]
This additional header is send to group notifications.

**Comment by AlfredSK** [comment]
> group notifications

Aha. What's this?

**Comment by annando** [comment]
Real mail clients (not Outlook of course) do group messages via the message-ids and reference-ids

**Comment by AlfredSK** [comment]
Ah! English is weird. :-) 'group' is a verb here, not a noun.

**Comment by annando** [comment]
The solution would be slightly over my head, so I would like to delegate it to @nupplaphil or @MrPetovan. Problem is that the PHPMailer addon seems to need the message id in a separate variable - but we include it in the additional headers.

The solution is to create a new class variable in our own mail class for message id. This could then be interpreted by the phpmailer addon. (And of course in the case that the addon doesn't take over, we have to read it and have to deal with it).

I could spend the rest of the evening trying to understand the way the classes work in this case - with the problem that it cannot be tested easily. So I hope that the others will take over.

**Comment by MrPetovan** [comment]
Good, since you have your work cut out for you here: https://github.com/friendica/friendica/issues/9165#issuecomment-694333463

**Comment by MrPetovan** [comment]
Still happens in 2020.09, see https://github.com/friendica/friendica/pull/9255#issuecomment-696248390

**Comment by AlfredSK** [comment]
When I deactivate the phpmailer add-on the notification mails have one Message-ID header.

**Comment by MrPetovan** [comment]
Thanks for the elaboration, it's great to troubleshoot.

**Comment by AlfredSK** [comment]
Without phpmailer add-on.

**Example 1: Comment to conversation**
```
To: alfred@libranet.de
Subject: [Friendica:Notify] Comment to conversation #86220466 by Michael Vogel (alfred@libranet.de)
Precedence: list\nX-Friendica-Host: libranet.de\nX-Friendica-Platform: Friendica\nX-Friendica-Version: 2020.09\nList-ID: <notification.libranet.de>\nList-Archive: <https://libranet.de/notifications/system>\nX-Friendica-Account: <alfred@libranet.de>\nReferences: <ec054ce7-185f-650e-f885-dbc719906155@librabox2.libranet.de>\nIn-Reply-To: <ec054ce7-185f-650e-f885-dbc719906155@librabox2.libranet.de>\nFrom: LIBRANET.de <admin@libranet.de>
Reply-To: LIBRANET.de <admin@libranet.de>
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="7-618145489-330360506=:36524"
Message-Id: <20200921185305.0B6DD2E81D15@libranet.de>
Date: Mon, 21 Sep 2020 18:53:05 +0000 (UTC)
From: www-data <admin@libranet.de>
```
Well, that line with "Precedence" looks weird. The headers have a wrong line break. :-) But only one Message-Id.

**Example 2: Someone tagged me**
```
To: alfred@libranet.de
Subject: [Friendica:Notify] utzer tagged you (alfred@libranet.de)
Precedence: list\nX-Friendica-Host: libranet.de\nX-Friendica-Platform: Friendica\nX-Friendica-Version: 2020.09\nList-ID: <notification.libranet.de>\nList-Archive: <https://libranet.de/notifications/system>\nX-Friendica-Account: <alfred@libranet.de>\nReferences: <ec054ce7-185f-650e-f885-dbc719906155@librabox2.libranet.de>\nIn-Reply-To: <ec054ce7-185f-650e-f885-dbc719906155@librabox2.libranet.de>\nFrom: LIBRANET.de <admin@libranet.de>
Reply-To: LIBRANET.de <admin@libranet.de>
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="4-330874097-806147933=:29123"
Message-Id: <20200921185005.3AA432E81CD9@libranet.de>
Date: Mon, 21 Sep 2020 18:50:05 +0000 (UTC)
From: www-data <admin@libranet.de>
```
Same here. Line breaks weird. Message-Id good.

**Comment by AlfredSK** [comment]
What is the current state? It's complicated. Emails are sent again. That's fixed. But...

**w/o phpmailer add-on:**

Only the newlines/linebreaks for additional headers don't work. Message-Id is okay.

**with phpmailer add-on:**

The newlines/linebreaks for additional headers are okay! But we have two Message-Id headers in notification mails **for users** like "someone commented on your post", "someone tagged you" and so on. But! Notification mails **for the admin** like "database update successful" are completely okay. 

**Example 3: Database update** 

```
To: admin@libranet.de
From: Mordor Social <admin@libranet.de>
Reply-To: Mordor Social <admin@libranet.de>
Subject: [Friendica Notify] Database update
Message-ID: <4PTB5yVW2MX0ef3rx69aYMlsd9amEq8LCSNi1Z5N0@librabox2.libranet.de>
X-Mailer: PHPMailer 6.1.4 (https://github.com/PHPMailer/PHPMailer)
Precedence: list
X-Friendica-Host: mordor.social
X-Friendica-Platform: Friendica
X-Friendica-Version: 2020.12-dev
List-ID: <notification.mordor.social>
List-Archive: <https://mordor.social/notifications/system>
MIME-Version: 1.0
```

**Comment by AlfredSK** [comment]
After pulling friendica/friendica-addons#1021 a notification mail with phpmailer addon:

```
Date: Wed, 23 Sep 2020 15:50:46 +0000
To: admin@libranet.de
From: Mordor Social <admin@libranet.de>
Reply-To: Mordor Social <admin@libranet.de>
Subject: =?UTF-8?Q?[Friendica:Notify]_Steffen_K9_=F0=9F=90=B0_tagged_you_(sauron@mordor.social)?=
Message-ID: <0b6b25a8-115f-6b6e-b9ae-a6d103454575@librabox2.libranet.de>
X-Mailer: PHPMailer 6.1.4 (https://github.com/PHPMailer/PHPMailer)
Precedence: list
X-Friendica-Host: mordor.social
X-Friendica-Platform: Friendica
X-Friendica-Version: 2020.12-dev
List-ID: <notification.mordor.social>
List-Archive: <https://mordor.social/notifications/system>
X-Friendica-Account: <sauron@mordor.social>
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="b1_xEH36h85IyyVt6k8dUfyIOdmpEQIHRii6TTkuu8qc"
```

There is **one** Message-ID header! 🎉 Let's see if the line breaks are fixed when the other PR has been merged...

**Comment by MrPetovan** [comment]
The line breaks seem fixed in your example, or have you altered the output in any way?

**Comment by AlfredSK** [comment]
No. The line breaks were ok before **with** phpmailer add-on. They're still wrong **without** phpmailer addon.
See also this [comment](https://github.com/friendica/friendica/issues/9142#issuecomment-696867670).

**Comment by nupplaphil** [comment]
the linebreaks are fixed with #9262 ... I forgot that using `'` instead of `"` isn't right in every case ;-)

**Comment by AlfredSK** [comment]
Last check: Line breaks are ok now. Only one Message-ID header. :-) With or without phpmailer the headers are correct now. 
Thank you for fixing it! 🎉

**Comment by nupplaphil** [comment]
... at least !! :-) Thanks for checking it!
